### ISSUE TITLE
 thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by ns-hxue** [guillaume-be/rust-bert#105]
Hi there,

I was trying to run the example codes, but I saw this error

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`: usage: /home/hongfa/rust-bert/target/debug/convert-tensor source.npz destination.ot', src/convert-tensor.rs:19:5

Any idea why?

**Comment by guillaume-be** [comment]
Hello @ns-hxue ,

This looks like missing parameters to the function call. This utility is meant to be used as a command line as follows:
`/path/to/binary/convert-tensor source.npz destination.ot` where `source.npz` is the source serialized numpy array and `destination.ot` is the name of the file for the output C-array.

This is not an example code as such, these are located in `/examples`.
I hope this helps

**Comment by cetra3** [comment]
For anyone else hitting this issue, if you are trying to run examples, the following will not work:

```
cargo run examples/token_classification.rs
```

This will invoke the default binary in `Cargo.toml` (which is `convert-tensor`)

You need to run:

```
cargo run --example token_classification
```
