### ISSUE TITLE
Make crate::bert::encoder public

### ISSUE THREAD

**Issue by lerouxrgd** [guillaume-be/rust-bert#108]
Would it be possible to make `crate::bert::encoder` public or export its components ?

This could be useful in order to implement models such as [CharBERT](https://github.com/wtma/CharBERT) which instantiate `BertLayer` and `BertPooler` directly.

**Comment by guillaume-be** [comment]
Hi @lerouxrgd 

Sure - I opened a PR (https://github.com/guillaume-be/rust-bert/pull/109) updating the visibility of `BertEncoder`. Do you need the `Layer` to be public as well or is the encoder sufficient?

**Comment by lerouxrgd** [comment]
Thank you for the PR !

As for the Rust code, if you want to keep changes even smaller, I think you can write something like:

```rust
let BertEncoderOutput { hidden_state, all_hidden_states, all_attentions } = self.encoder.forward_t(...);
```

Actually yes, `BertLayer` and `BertPooler` would also need to be public in order to implement `CharBERT`.

The reason is that the output of each layer is merged, processed, and split again with a character-level embedding (as you can see [here](https://github.com/wtma/CharBERT/blob/6b9bf71fada92468c7596b9a6fc173a274cc5b58/modeling/modeling_bert.py#L404)).

**Comment by guillaume-be** [comment]
Hi @lerouxrgd , just merged the related changes - please let me know if this works for you.
For info, I am planning on a release by the end of next week (including a MobileBERT support).

**Comment by lerouxrgd** [comment]
Everything looks good !
Thank you for the quick action !
