### ISSUE TITLE
About Activation visibility in Config implementors

### ISSUE THREAD

**Issue by lerouxrgd** [guillaume-be/rust-bert#110]
Hi again,

It looks like `Config` implementors, surch as `BertConfig`, have a public `Activation` field but this enum is not public. 
It is thus impossible to store it as a field in a struct (its type must be known and accessible).

I feel that publicly exposed types should be public, what do you think ?

Also, do you think `BertConfig` and its friends could implement `Clone` ? It seems that nothing is preventing it (`Activation` is clonable).

**Comment by guillaume-be** [comment]
Hi @lerouxrgd 

Sounds reasonable - pushing proposed related changes via https://github.com/guillaume-be/rust-bert/pull/111

**Comment by lerouxrgd** [comment]
Thank you for the quick action again !

Actually in your commit `Activation` is public within `common` which is not public. So in the end it is still not public.

**Comment by lerouxrgd** [comment]
Everything is fine with your last commit, thank you again !
