### ISSUE TITLE
replacing the python utils with rust code?

### ISSUE THREAD

**Issue by rustrust** [guillaume-be/rust-bert#12]
Do you mind going ahead with replacing the python utilities with rust code? 

The python utilis scripts are segfaulting (!!) on my system (possibly due to out of memory). Even the first import alone causes a segfault. I've been careful to create a fresh venv using python 3.6 and installed torch torchvision and transformers only in the venv on an up-to-date linux system running cuda 10.1 (several different versions of python actually including 3.7 and 3.8).

This line alone causes a segfault:
```
from transformers import BERT_PRETRAINED_CONFIG_ARCHIVE_MAP
```

**Comment by guillaume-be** [comment]
Hello,

I will have a look at Rust utilities for the download and conversion of the models. This would involve hard-coding the location of the remote resources which I wanted to avoid in case the Huggingface model endpoints are changing. 

However, please note that the download scripts have all been tested and are running in a controlled CI Linux environment. The CI setup can be seen at https://travis-ci.com/guillaume-be/rust-bert/jobs/295652126 

Regarding the segfaults, could you post the error message you are getting? The `BERT_PRETRAINED_CONFIG_ARCHIVE_MAP` is just a small Python dictionary with about 20 string key/value pairs. This should not cause any system to Segfault (see 
https://github.com/huggingface/transformers/blob/master/src/transformers/configuration_bert.py). The Transformers library is used by thousands and the scripts proposed should be working fine - I am happy to support wherever I can to get you started.

**Comment by guillaume-be** [comment]
Hello,

Sorry for the delayed response on this as I was working on a more convenient alternative for a pure Rust utilization. I have worked with the Transformers' authors (Thank you to @julien-c and the Hugging Face team for the support), to offer Rust-compatible model weights for direct download in the library. This means that users no longer need to use Python if they want to load a set of pre-trained weights.

Please refer to the updated [documentation](https://docs.rs/rust-bert/0.7.0/rust_bert/) for examples on how to use the library.

**Comment by rustrust** [comment]
it works brilliantly thanks. for other people who come across this bug, you need to run (and make sure that you have ```git pull origin master``` if this hasn't shipped yet) :

```cargo run --example download_all_dependencies```
