### ISSUE TITLE
Hello, is it possible to try/add gpt-neo model?

### ISSUE THREAD

**Issue by Qeenon** [guillaume-be/rust-bert#132]
There is one https://github.com/EleutherAI/gpt-neo/
I'd really like to try this one

**Comment by guillaume-be** [comment]
Hello @Qeenon ,

The released models (*XL* and *2.7B*) are implemented using mesh-tensorflow (targeting TPUs I assume) and would need to be re-implemented/converted to Pytorch snapshot to be loaded in the library. I am not sure how much better these would be compared to GPT2 - and would probably want to evaluate their potential before looking to port them to Rust.

It looks like the EleutherAI team has mostly moved to a new repository for further scaling (https://github.com/EleutherAI/gpt-neox), leveraging what looks like a Megatron architecture (released by Nvidia at https://github.com/NVIDIA/Megatron-LM). Implementing the Megatron architecture would be possible, but may require significant implementation work to support multi-GPU/distributed settings for the larger models. There is unfortunately no equivalent to DeepSpeed for Rust and *tch-rs* (yet) as far as I know.

I have limited capacity to implement this model - and would suggest evaluating again when a significantly larger snapshot (e.g. their 10B project) is released and when the EleutherAI reaches a more stable status. Please also note that implementing models released for the [Transformers library](https://github.com/huggingface/transformers) is usually also significantly more straight-forward.

**Comment by guillaume-be** [comment]
@Qeenon 
GPT-Neo is now available in Hugging Face's model hub and `transformers`. I will start working on an implementation in the next few days.

**Comment by guillaume-be** [comment]
Now published as part of v0.15.0
