### ISSUE TITLE
Porting prefix_allowed_tokens for text generation

### ISSUE THREAD

**Issue by paulbricman** [guillaume-be/rust-bert#152]
Hi, and thanks for maintaining such an awesome package!

I was wondering whether the `prefix_allowed_tokens` parameter of the [generate() function](https://huggingface.co/transformers/main_classes/model.html?highlight=prefix_allowed_tokens#transformers.generation_utils.GenerationMixin.generate) from HF transformers could, at least in principle, be ported to rust-bert.

In HF transformers, this parameter receives a function as an argument. This function outputs a list of *allowed* candidate token ids for the generation of the next token. It takes as input a list of the token ids which have been previously generated, prior to that step.

Why would that be helpful? It would make it possible to force the generation models to:
- "quote" from an existing pool of candidate strings, such as [wikipedia entries in this paper](https://arxiv.org/abs/2010.00904)
- "quote" consecutive tokens from a document, such as [extracting phrases from a document](https://github.com/Psionica/Dual/blob/master/backend/core.py#L126)
- "quote" any token from a restricted pool of tokens, such as multiple choice options, numbers etc.
- stop the generation process after a set number of sentences or paragraphs (by counting already generated sentences/paragraphs and forcing an eos token if exceeding a certain threshold)
- ...

A `prefix_allowed_tokens` parameter would make it really accessible to tweak the generation process in many ways. I'm not sure how it would be implemented, though. Not even sure whether you can pass functions as arguments in Rust. But could such a function at least be hardcoded in `generation_utils` or something?

**Comment by guillaume-be** [comment]
Hi @paulbricman ,

In general I believe this would be feasible. It is possible to pass functions or closures as arguments to functions (see for example https://doc.rust-lang.org/rust-by-example/fn/closures/input_parameters.html or https://doc.rust-lang.org/book/ch19-05-advanced-functions-and-closures.html). 

I am still not sure at which level of the API this functionality should be exposed, but most likely this will be an extension of the `generate` method of the `LanguageGenerator` public trait. This will result in breaking changes (modifying the signature of a public trait). I am currently working on some unrelated changes that will result in an update of the `generate` method too - and I suggest to implement these changes at the same time. 

What would help in the meantime is if you could prepare a small example/gist illustrating how this functionality is used in Python's Transformers that could also serve as a test case to validate the Rust implementation. It would be even better if this would use an architecture already implemented in this library.

**Comment by paulbricman** [comment]
Hi @guillaume-be,

I packaged up a tiny example in [this colab notebook](https://colab.research.google.com/drive/1yD8AIfv4V-UXCV9p5PlFDRBas_KiP2rZ?usp=sharing) using GPT-2. The function used to restrict the pool of candidates is pretty straightforward in this case. In general, it allows any token to be used, except for the eos one. However, if a token denoting a new line has already been generated before, the function prescribes eos as the only allowed token. This way, it forces the generation to stop when finishing a paragraph-like structure, and not beforehand.

Even if this example merely enables the use of some specific stopping sequence (similar to the GPT-3 environment pictured below), the prescribed function could have its own clever logic, say for quoting from a document or some other thing entirely.

![image](https://user-images.githubusercontent.com/20104026/119500950-09e6b200-bd71-11eb-9b0a-a58b013cfa13.png)

**Comment by guillaume-be** [comment]
Hi @paulbricman ,

Thank you - this is very helpful and I understand how such a function can be useful. I am starting to work on an implementation, I am still a bit undecided as to how to best modify the API (this will result in breaking changes as Rust does not support optional function arguments).

My first idea is:
- Expose an additional function parameter to `generate`, `generate_indices` and `generate_from_ids_and_past` in the `LanguageGenerator` trait. This is the "lower-level" API exposed when creating directly for example a `GPT2Generator`.
- Keep the "high-level" api methods for `TextGenerationModel`, `TranslationModel` and `SummarizationModel` unchanged. Most users are unlikely to pass this method for text generation and it is cumbersome to have to pass `None` to the `generate` or `summarize` methods for these pipelines
- We could still offer the possibility to provide such a ` prefix_allowed_tokens_fn` for these top-level pipelines via the `Config`. This would possibly still result in breaking change, but we could default this `prefix_allowed_tokens_fn` field to None in the configurations (e.g. `TextGenerationConfig`) and expert users can still update it as follows. The only drawback is that the function would remain fixed for a given model instance and cannot be changed from input to input (is it a fair assumption?):
```rust 
let generate_config = TextGenerationConfig {
	model_type: ModelType::GPT2,
	max_length: 30,
	prefix_allowed_tokens_fn: my_custom_function,
	..Default::default()
};
```

Do these API changes seem reasonable and would fit your typical use?

**Comment by paulbricman** [comment]
Hi @guillaume-be,

Thanks for tackling this feature request. Requiring the function argument in lower-level methods while not requiring it in higher-level ones seems perfectly reasonable to me. The config workaround to enable the feature for top-level pipelines as well makes sense. 

That said, I'm a bit skeptical about your assumption for fixing the `prefix_allowed_tokens_fn` from input to input. For instance, in the project I'm working on which runs on HF transformers, I use [several different "behaviors" prescribed](https://github.com/Psionica/Dual/blob/master/backend/core.py#L104) through `prefix_allowed_tokens_fn` to the language model. `finish_paragraph` and `finish_sentence` prescribe behavior similar to the tiny Colab example I sent in before, while `parse_args` actually forces the model to quote from a string (in this case a message sent by the user to this language model). And all those behaviors are applied using a single instance of the model.

Now that I'm writing this, I'm thinking: could `TextGenerationConfig` take in a fix function, a function whose behavior could change based on some other variable accessible from it? I think this could at least be done with some local files? Like, [in the other project I'm specifying the behavior by providing a string argument](https://github.com/Psionica/Dual/blob/master/backend/core.py#L96). But wait, that's still a fix function. Hm...

**Comment by guillaume-be** [comment]
Hello @paulbricman ,

I understand that `prefix_allowed_tokens_fn` may need to be changed from call to call, and believe therefore it makes most sense to leave it out of a static configuration for the high-level pipelines. I have just published a PR that implements the `prefix_allowed_tokens_fn` at the lower-level API of `LanguageModels`. 

The example below reproduces the case you provided in the notebook:

```rust
extern crate anyhow;

use rust_bert::gpt2::{
    GPT2Generator, Gpt2ConfigResources, Gpt2MergesResources, Gpt2ModelResources, Gpt2VocabResources,
};
use rust_bert::pipelines::generation_utils::{GenerateConfig, LanguageGenerator};
use rust_bert::resources::{RemoteResource, Resource};
use tch::Tensor;

fn force_one_paragraph(_batch_id: i64, previous_token_ids: &Tensor) -> Vec<i64> {
    let paragraph_tokens = [198, 628];

    for paragraph_token in paragraph_tokens.iter() {
        if previous_token_ids
            .iter::<i64>()
            .unwrap()
            .collect::<Vec<i64>>()
            .contains(paragraph_token)
        {
            return vec![50256];
        }
    }
    (0..50255).collect()
}

fn main() -> anyhow::Result<()> {
    //    Set-up masked LM model
    let generate_config = GenerateConfig {
        max_length: 56,
        model_resource: Resource::Remote(RemoteResource::from_pretrained(Gpt2ModelResources::GPT2)),
        config_resource: Resource::Remote(RemoteResource::from_pretrained(
            Gpt2ConfigResources::GPT2,
        )),
        vocab_resource: Resource::Remote(RemoteResource::from_pretrained(Gpt2VocabResources::GPT2)),
        merges_resource: Resource::Remote(RemoteResource::from_pretrained(
            Gpt2MergesResources::GPT2,
        )),
        do_sample: false,
        num_beams: 1,
        ..Default::default()
    };
    let model = GPT2Generator::new(generate_config)?;

    let input_context_1 = "Rust is a";
    let input_context_2 = "There was a ";
    let output = model.generate(
        Some(&[input_context_1, input_context_2]),
        None,
        None,
        None,
        None,
        Some(&force_one_paragraph),
    );

    for sentence in output {
        println!("{:?}", sentence);
    }
    Ok(())
}
```

Regarding your question, I believe the best way to change the function programmatically would be to have a "`function_factory`" in your code that would take an arbitrarily large number of arguments and return a function of type `Fn(i64, &Tensor) -> Vec<i64>` which you could pass to the `generate` functions.

**Comment by paulbricman** [comment]
This looks really awesome, thanks so much for tackling this! The factory pattern makes sense, I'll have to look into it but I guess it's analogous to the factory or builder design patterns in Java.

Is there anyway I can help regarding this PR?

**Comment by guillaume-be** [comment]
@paulbricman the PR is complete and should be ready to use on master.

Please see below an example illustrating the factory concept (where the `<eos>` id can be set dynamically) - I hope this helps:
```rust
extern crate anyhow;

use rust_bert::gpt2::{
    GPT2Generator, Gpt2ConfigResources, Gpt2MergesResources, Gpt2ModelResources, Gpt2VocabResources,
};
use rust_bert::pipelines::generation_utils::{GenerateConfig, LanguageGenerator};
use rust_bert::resources::{RemoteResource, Resource};
use std::ops::Deref;
use tch::Tensor;

fn generic_force_paragraph_factory(eos_id: i64) -> Box<dyn Fn(i64, &Tensor) -> Vec<i64>> {
    Box::new(move |_batch_id: i64, previous_token_ids: &Tensor| {
        let paragraph_tokens = [198, 628];

        for paragraph_token in paragraph_tokens.iter() {
            if previous_token_ids
                .iter::<i64>()
                .unwrap()
                .any(|x| x == *paragraph_token)
            {
                return vec![eos_id];
            }
        }
        (0..50255).collect()
    })
}

fn main() -> anyhow::Result<()> {
    //    Set-up masked LM model
    let generate_config = GenerateConfig {
        max_length: 56,
        model_resource: Resource::Remote(RemoteResource::from_pretrained(Gpt2ModelResources::GPT2)),
        config_resource: Resource::Remote(RemoteResource::from_pretrained(
            Gpt2ConfigResources::GPT2,
        )),
        vocab_resource: Resource::Remote(RemoteResource::from_pretrained(Gpt2VocabResources::GPT2)),
        merges_resource: Resource::Remote(RemoteResource::from_pretrained(
            Gpt2MergesResources::GPT2,
        )),
        do_sample: false,
        num_beams: 1,
        ..Default::default()
    };
    let model = GPT2Generator::new(generate_config)?;

    let input_context_1 = "Rust is a";
    let input_context_2 = "There was a ";

    let custom_force_paragraph = generic_force_paragraph_factory(50256);

    let output = model.generate(
        Some(&[input_context_1, input_context_2]),
        None,
        None,
        None,
        None,
        Some(custom_force_paragraph.deref()),
    );

    for sentence in output {
        println!("{:?}", sentence);
    }
    Ok(())
}
```

**Comment by paulbricman** [comment]
Perfect, thanks again! That was super fast
