### ISSUE TITLE
How would you approach implementing the scoring of given completions in text generation? 

### ISSUE THREAD

**Issue by paulbricman** [guillaume-be/rust-bert#161]
Hi,

When generating text using beam search, there's a mechanism behind-the-scenes for scoring the candidate completions by their likelihood-ish, with one candidate coming from each beam. I think something similar is happening when using sampling and returning multiple possible completions. I was wondering whether it would be possible to perform such a scoring/ranking of *custom* completions, which are simply given (i.e. a `Vec<String>`) and have nothing to do with beam search.

Why? I'm experimenting with implementing semantic search using text generation. I know semantic search is traditionally done using [a retrieve/re-rank paradigm based on separate specialized models](https://www.sbert.net/examples/applications/retrieve_rerank/README.html), but I have a hunch that OpenAI is using their actual text generation models for semantic search as well. They're asking users to mention a specific GPT-3 model to use in their semantic search requests:
![image](https://user-images.githubusercontent.com/20104026/122031049-fdd19b80-cdd6-11eb-8544-c048c70f2d9d.png)

I think this is implemented by determining how likely each document is as a completion to the query (or a clever short prompt based on the query). The screenshot from a demo of theirs shows the following candidate paragraphs from a web page with their scores, given a query:
![image](https://user-images.githubusercontent.com/20104026/122031212-2bb6e000-cdd7-11eb-8ab5-1468ca09de30.png)

So what I wanted to ask is how would you approach implementing this scoring of given completion based on a prompt? Is there some method buried somewhere for obtaining the likelihood-ish of a sequence of tokens given a model and possibly a prompt? Should I try to regenerate the candidate documents token by token and check how likely the ground-truth token at that location is? I feel that would take ages, but maybe something like teacher-forcing to batch all "prefixes" and determining all next tokens at each location at once. Although I can only run on CPU, so this wouldn't help that much.

I'm really curious to hear whether you have any thoughts on this. Another possible usecase for such a feature besides semantic search might be ranking candidate speech-to-text outputs by likelihood.

Oh actually as I was wrapping this up I thought: what if by using the `allowed_tokens` feature you implemented recently, you could force/constrain the model to only write out the candidate documents. Then beam search in this regime would essentially give you the most likely candidate documents as completions. In the case in which you don't have other suggestions, I think this is what I'll go with. With a diversity penalty so that not all beams give you the same candidate.

**Comment by guillaume-be** [comment]
Hello @paulbricman ,

I understand your use-case, and I believe using the `prefix_allowed_tokens_fn` is indeed a good idea. You could essentially generate a custom version of this function (as discussed in https://github.com/guillaume-be/rust-bert/issues/152) that would take in the text you are trying to score, tokenize/encode it and store the tokenized version in the function. At each step, you could then length of the `previous_token_ids` passed to the function and look-up the only allowed token id. 

You could even score multiple texts as a batch by using the `batch_id` parameter of this `prefix_allowed_tokens_fn` to have multiple texts you'd perform lookup on based on their batch id (I think this would be more robust than using beams and a diversity penalty).

The only thing missing would be to return the score of the generated sequence. This is currently not implemented in this library but I update the code to allow returning it along with the generated sequence.

**Comment by paulbricman** [comment]
Thanks again for the prompt reply and for the feedback on the suggested implementation!

Wouldn't constraining the model to "regurgitate" any of the candidate documents in one go be more efficient than scoring all candidate completions separately and keeping track of eventual scores? This way, all beams would be drawn towards the most likely documents from the very beginning, without having to painstakingly "beam through" single candidate documents separately. Do you think that this gain in efficiently would result in significantly poorer performance?

To illustrate, let `C={"Those cats are amazing.", "Those dogs are amazing.", "Rust is a systems language."}` be the set of candidate documents and `P="The following sentence is about animals. "` be the prompt. At the beginning, `prefix_allowed_tokens_fn` would allow the "Those" and "Rust" tokens. For a beam that generated "Those" before, it is now allowed to choose from " cats" and " dogs", and so on. I mean, it doesn't even have to be beam search, it can be sampling with the same constraints.

**Comment by guillaume-be** [comment]
The way I see the `prefix_allowed_tokens_fn` funtion to work in that case would be something along the lines of:

```rust
fn force_one_paragraph(batch_id: i64, previous_token_ids: &Tensor) -> Vec<i64> {
    let encoded_output = vec![
       vec![21, 45, 35, 48, 76],   // <-- encoded value of "Those cats are amazing."
       vec![35, 48, 52, 36, 87],   // <-- encoded value of "Rust is a systems language."
    ];

    let current_position = previous_token_ids.len();
    let forced_token_output = encoded_output[batch_id][current_position ]
    return vec![forced_token_output];
}
```

And then you would call `generate(["Those cats are amazing.", "Rust is a systems language."])` with no sampling and no beam search (you are enforcing the token values anyway). This would return a score for each of the sequences returned which you could then compare.

**Comment by paulbricman** [comment]
Oh, I see, that's conceptually simpler. But this can't yet be done because there's no way of getting that score, right?

**Comment by guillaume-be** [comment]
Hello @paulbricman ,

Yes this is not feasible in the current version of the library. I have just opened a pull request adding the optional calculation of the log-probabilities for generated sequences in the low-level generation API. Please see the updated GPT2 tests as an illustration of how this would work.

**Comment by paulbricman** [comment]
That's awesome, @guillaume-be! The tests look pretty straight-forward. I'll also send a link here at some point (way after you close the issue) to the file I'll use this feature in, to hopefully help others looking for more examples.
