### ISSUE TITLE
"generate" outputs using certain decoding parameters?

### ISSUE THREAD

**Issue by paulbricman** [guillaume-be/rust-bert#164]
This one took some figuring out...

```rust
let doc = "Calculate. . ."; // note the weird spaces!
let doc_ids = tokenizer.convert_tokens_to_ids(tokenizer.tokenize("Calculate. . .")); // [9771, 3129, 378, 13, 764, 764]
```

If I force a text generation model to "quote" consecutive tokens ids from the document `doc` when generating (by specifying this behavior in prefix_allowed_tokens_fn), I get the output `Calculate...`, which annoyingly misses some spaces (and is therefore not really a quote). This wouldn't really be a problem in open-ended text generation, but I'm searching for the specific documents which have been "quoted" during completion, meaning this slight mismatch is a bit of a struggle. 

After digging a bit, I found that those two work slightly differently:

```rust
let doc_ids = vec![9771, 3129, 378, 13, 764, 764];
let x = tokenizer.decode(doc_ids, true, true); // Calculate...
let y = tokenizer.decode(doc_ods, false, false); // Calculate. . .
```

So I thought that maybe `generate` uses the first decoding approach. My question is, can I get output from `generate` which is decoded using the second decoding approach above? This might mean maybe somehow getting the raw ids from `generate` to use the second decoding approach separately. Or maybe configuring the tokenizer used by the model to work in a certain way (I think this is private and pretty inaccessible).

**Comment by paulbricman** [comment]
Hm, again a late workaround: I could first tokenize my documents, then decode them with the first decoding approach, then tokenize them back again. This might result in both context documents and generation output having the same style-ish.

**Comment by guillaume-be** [comment]
Hello @paulbricman ,

Would the [`generate_indices`](https://docs.rs/rust-bert/0.15.1/rust_bert/pipelines/generation_utils/trait.LanguageGenerator.html#example-1) method of the public trait `LanguageGenerator` work? You can use this method to generate token indices and then implement custom decoding routines.

**Comment by paulbricman** [comment]
That seems way more appropriate, thanks! I'll have a look tomorrow and report back.

**Comment by paulbricman** [comment]
Yeah, it works well now :+1: I just switched from `generate` to `generate_indices` and then mapped the outputs using the custom decoding method.
