### ISSUE TITLE
Feature extraction pipeline

### ISSUE THREAD

**Issue by pjankiewicz** [guillaume-be/rust-bert#168]
Would extracting features from BERT models would be possible as it is in huggingface transformers?

https://huggingface.co/transformers/main_classes/feature_extractor.html

It is an important task if you want to build something like a semantic search engine.

**Comment by guillaume-be** [comment]
Hello @pjankiewicz ,

I am not sure I fully understand what you mean by feature extractor. The link you provided points to pre-processing pipelines for multi-modal models (e.g. audio file pre-processing) which does not seem directly related to semantic search engines.

If you are looking for the generation of sequence-level embeddings as proposed by [sbert](https://www.sbert.net), I would recommend looking into the [rust-sbert](https://github.com/cpcdoy/rust-sbert) project that aims at porting the Python sentence-transformer architectures to Rust.

**Comment by pjankiewicz** [comment]
@guillaume-be maybe I didn't specify - I was talking about getting the embeddings for text. The link is about general use case when you want to extract embedding from a sequence - below I add another link specifically for pipelines.

Feature Extraction is I think perfectly acceptable in parallel to other tasks that you can get from the model https://huggingface.co/transformers/v2.11.0/main_classes/pipelines.html#transformers.FeatureExtractionPipeline

```
“feature-extraction”, for extracting features of a sequence. 
All models may be used for this pipeline. 
```
I will check sbert (thanks for the link)

**Comment by lsb** [comment]
@guillaume-be my understanding is that this is the model without a head, if one wants to add a masked language modeling head (predicting one of tens of thousands of tokens), a sentiment classifier head (predicting positive/negative), et cetera

**Comment by guillaume-be** [comment]
Hello @lsb - sentence embeddings actually include a few specific layers on top of the model backbones. Please see the following as an example of a sentence transformer using mean pooling: https://www.sbert.net/examples/applications/computing-embeddings/README.html#sentence-embeddings-with-transformers .

I agree that users looking to use sentence transformer models may use one of the models implemented in this crate (base model without task specific head as you mention) and implement the (light) additional layers to get a full sentence transformer implementation. Alternatively work on a PR has been proposed today (https://github.com/guillaume-be/rust-bert/pull/250) to implement this feature as part of pipelines
