### ISSUE TITLE
Problems Compiling Rust-Bert Library for target x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by Tiberius202** [guillaume-be/rust-bert#169]
I'm trying to compile a staticlib with the cargo build argument x86_64-pc-windows-gnu and I get a wall of errors. I need a staticib because I am trying to compile the rust code into a c library, so I can call the functions from c code.

[Errors.txt](https://github.com/guillaume-be/rust-bert/files/6750152/Errors.txt)

I have tried a couple things to get around this. The main one that worked was removing the "--target=x86_64-pc-windows-gnu", but doing so ruined the c library I want (I think it mangled the names) on both my project and a similiar one. However, removing the target made the project build.

I don't believe this is a problem with rust-bert or my code but caused by libtorch / torch-sys. The build error happens while compiling torch-sys and most of the errors say something about libtorch. I have seen similar errors online when incompatible versions of libtorch and tch are used but I have downloaded libtorch CPU 1.8.1 and am using tch 0.4.1. 

Here is a copy of the relevant parts of my cargo.toml.

[lib]
crate-type = ["staticlib"]

[dependencies]
rust-bert = "0.15.1"
anyhow = "1.0.40"
tch = "0.4.1"
libc = "*"

If you need anymore information or have any suggestions, let me know.

Thank You!

**Comment by guillaume-be** [comment]
Hello @Tiberius202 ,

Thank your for raising this issue. I was able to reproduce the error when compiling the _tch_ dependency, and it therefore does not seem to be directly related to _rust-bert._ I see you have opened an issue at https://github.com/LaurentMazare/tch-rs/issues/380 - would it be OK if I close this issue and continue the conversation on the _tch_ side?

**Comment by Tiberius202** [comment]
You're right. Thank you for the help. 

I actually opened an issue on the tch project github as well and was able to get through to LaurentMazare. I will stay in contact with him about this problem on the tch issues page.
