### ISSUE TITLE
Increasing the max number of tokens for the part of speech pipeline/model

### ISSUE THREAD

**Issue by Tiberius202** [guillaume-be/rust-bert#177]
I am using the part of speech tagging pipeline and it works well on small texts.

On larger texts, there seems to be a token limit to either the model or .rs as the program can process a very large nonsensical word (almost a megabyte), but cuts short a normal text at about the 600th word (a few kilobytes in).

I am passing the entire text in as a single &str element into the predict. I do this as I am unsure if there is a steadfast rule for breaking up the text as to not split words or sentences in half. 

Is there a variable in the model's config resources or the tokenizer's resources that can change this max size? Is it some kind of code in pos_tagging.rs?

What is the best way to get around this size limit and analyze a much larger text?

Thank you for your time

**Comment by guillaume-be** [comment]
Hello @Tiberius202 ,

Thank you for raising this. The current maximum length for token classification is indeed currently hard-coded and set to 128 tokens (https://github.com/guillaume-be/rust-bert/blob/5979e0bff9ac46a9a47d487ec164b1eb5762e904/src/pipelines/token_classification.rs#L621). This is too limiting for most models that can usually take input sequences of up 512 tokens or more (at the cost of a quadratic increase in computational cost).

I am working on a fix that would increase the maximum length to use the limit of the model itself (will increase to 512 for MobileBert). I will also look into a pipeline update that will actually split the input in sliding windows to take arbitrarily long input sequences - I will let you know as soon as I have an update ready.

**Comment by Tiberius202** [comment]
Thank you for making these changes, although I am not really sure how to work them. I am using the pos_tagging.rs pipeline you provided and making sure to run cargo clean and get the rust-bert 0.15.1 version. I can only assume the pos_tagging model is itself capped at about 128 tokens.

However, I don't know if this will be necessary. I thought perhaps the model ran in linear time based on the number of sentences, but since the model is quadratic based on size we can always come up with a way to split our inputs based on sentences.

I saw in the update you put something about a sliding window system. I would really like to use this feature, but I don't really know how. 

Sorry to use your time on my inexperience.

**Comment by guillaume-be** [comment]
Hello @Tiberius202 ,

These updates do not require any change on your end: if your input is shorter than 512 tokens, it will be processed as a single input. If it is longer, it will automatically be split in sliding windows and processed as a batch. The changes have been implemented, but not released yet.

They will be part of the 0.16.0 version which I am planning to release in the next few days.

**Comment by Tiberius202** [comment]
Ahh, that makes a lot of sense.

Can't wait for the new update. Thank you!

**Comment by guillaume-be** [comment]
@Tiberius202 I have released the changes this morning, please update the your rust-bert dependency to `0.16.0` if you would like to leverage these changes
