### ISSUE TITLE
Porting bad_words_ids from python Transformers for GPT text generation

### ISSUE THREAD

**Issue by kingpalethe** [guillaume-be/rust-bert#181]
Thanks for this interesting library.

We're running into a performance bottleneck with python Transformers with GPT-NEO inference. 

The more words we add to `bad_words_ids`, the slower the generation is.

Here is the relevant code in Transformers. 

https://github.com/huggingface/transformers/blob/b1198a8440cc05f569b0bc22038993a1e5e707ab/src/transformers/generation_logits_process.py#L345

And our note on the forum:

https://discuss.huggingface.co/t/gpt2-many-bad-words-ids-leading-to-slow-text-generation/9721

In our tests, if we add 2000 `bad_words_ids`, our generation takes 2x as long. 

It occurs to me (naively?) that this is exactly the kind of function that **should be much faster with Rust, instead of Python**.

Questions:

1) Am I wrong? Would this actually be faster in Rust?
2) Would it be difficult or impossible to port the `bad_words_ids` so it could be used to `generate` text with `GPT` with this rust package?

thanks!

**Comment by guillaume-be** [comment]
Hello @kingpalethe ,

Thank you for the suggestion. The implementation was rather straight-forward, and I have opened a PR to implement this feature in the library. The behaviour in Rust is likely to at least match the Python performance.

Please note that looking into the Python implementation, I have also noted some areas for performance improvement. I could reproduce a significant slowdown using a large number of bad word ids (~2000 words sampled randomly). The handling of bad word ids caused a high number of exchanges between the GPU and CPU causing a significant slowdown. I have also opened a pull request for the Python implementation (see https://github.com/huggingface/transformers/pull/13433) which may solve your issue in Python as well.

**Comment by kingpalethe** [comment]
Awesome, thanks for our attention to this.
