### ISSUE TITLE
Maybe support sentence-transformers

### ISSUE THREAD

**Issue by Kavan72** [guillaume-be/rust-bert#185]
It would be great if this lib support sentence-transformers. I've found one repo which is created top on this project, you can find here https://github.com/mladvladimir/rust-sentence-transformers

**Comment by Kavan72** [comment]
@guillaume-be any news on this?

**Comment by guillaume-be** [comment]
Hello @Kavan72 ,

Thank you reaching out. This is still on the list of things I would like to have a look at, but I haven't had a chance to get to it yet. The past few months have been eventful, I am hoping to have more time and look into this. Have you had a chance to check the `rust-sbert` crate by any chance? Is that the kind of implementation you are looking for?

**Comment by Kavan72** [comment]
Hey @guillaume-be, 

Thanks for replying. I can understand maintaining an open-source project is not that easy. Also, I've checked `rust-sbert` but my problem is for api I've to use another lib.

**Comment by guillaume-be** [comment]
support for sentence embeddings added via https://github.com/guillaume-be/rust-bert/pull/250
