### ISSUE TITLE
Documentation for passing in arguments to generate method?

### ISSUE THREAD

**Issue by kingpalethe** [guillaume-be/rust-bert#186]
Thanks for this excellent library.

We're trying to benchmark our GPT-NEO use case and are struggling to pass in arguments to `generate`.

This GPT-NEO example, here, shows the creation of a `TextGenerationConfig`, which allows for customizing the model output:

https://github.com/guillaume-be/rust-bert/blob/master/examples/generation_gpt_neo.rs

This works well, but if the `TextGenerationConfig` were to change, by, for example, modifying the `max_length`, then the model would have to be re-loaded, which isn't practical for a performance critical application.

Clearly we need to somehow pass `max_length` and other arguments in *at runtime*. In python, we use this documentation:

https://huggingface.co/transformers/main_classes/model.html?highlight=generate#transformers.generation_utils.GenerationMixin.generate

Specifically, we are able to adjust parameters like `num_beams` and `max_length` with the python library without re-loading the model.

We're struggling to figure out how to do the same with rust-bert. 

We do see, directly on the Github home page (https://github.com/guillaume-be/rust-bert ), what looks like an example of doing this with `generate`:

![Capture](https://user-images.githubusercontent.com/11775831/138292244-bc8b1388-980f-4e8a-8f47-4e62f9f80463.PNG)

Specifically, it looks like these 13 arguments are passed in: `0, 30, true, false, 5, 1.2, 0, 0.9, 1.0, 1.0, 3, 3, None`

But, we're struggling to find any documentation for these arguments. 

We can also see some arguments passed in here, 8 arguments: https://github.com/guillaume-be/rust-bert/pull/182/commits/91b061f0ed8f52d7d17b9134e20027c36e46e026#diff-4cf8f83a97380982884e41a9fcf0b47fa101648bd5898599ccb15da33386133fR502

And some arguments passed in here, 18 arguments: https://github.com/guillaume-be/rust-bert/blob/master/src/pipelines/generation_utils.rs#L248

But I think we're chasing our tail here.

**Comment by kingpalethe** [comment]
Great, thanks, looking forward to that update, as yes, we need to use some of those latter options for example `num_beams` .

**Comment by guillaume-be** [comment]
Hello @kingpalethe ,

I have opened a pull request that exposes additional generation options on an existing model. This includes the generation options that are provided by the Python Transformers library. Please note that this API is only exposed when working with the `LanguageGenerator` trait of the models (for example `GPT2Generator`), and not from the high-level task-specific pipelines such as translation - in order to keep the top-level API lightweight.

This changes now allow the following:
```rust
extern crate anyhow;

use rust_bert::gpt2::GPT2Generator;
use rust_bert::pipelines::generation_utils::{GenerateOptions, LanguageGenerator};

fn main() -> anyhow::Result<()> {
    //    Set-up model
    let model = GPT2Generator::new(Default::default())?;

    let input_context = "The dog";
    let second_input_context = "The cat was";

    let generate_options = GenerateOptions {
        min_length: Some(42),
        num_beams: Some(3),
        ..Default::default()
    };

    let output = model.generate(
        Some(&[input_context, second_input_context]),
        Some(generate_options),
    );

    for sentence in output {
        println!("{:?}", sentence);
    }

    let generate_options = GenerateOptions {
        max_length: Some(15),
        num_beams: Some(1),
        ..Default::default()
    };

    let output = model.generate(
        Some(&[input_context, second_input_context]),
        Some(generate_options),
    );

    for sentence in output {
        println!("{:?}", sentence);
    }

    Ok(())
}

```

**Comment by kingpalethe** [comment]
Thanks, will be trying this out shortly.
