### ISSUE TITLE
Question:Help: BertForSequenceClassification  Multilabel custom model num_labels=68

### ISSUE THREAD

**Issue by remotejob** [guillaume-be/rust-bert#196]
I have a multilabel custom model [https://huggingface.co/remotejob/gradientclassification_v0/](https://huggingface.co/remotejob/gradientclassification_v0/)

Working code:
===============================
from transformers import BertTokenizerFast, BertForSequenceClassification

from datasets import load_dataset
model_path = 'remotejob/gradientclassification_v0'
max_length = 512

model = BertForSequenceClassification.from_pretrained(model_path, num_labels=68)
tokenizer = BertTokenizerFast.from_pretrained(model_path)

def get_prediction(text):
    # prepare our text into tokenized sequence
    inputs = tokenizer(text, padding=True, truncation=True, max_length=max_length, return_tensors="pt")
    # perform inference to our model
    outputs = model(**inputs)
    # get output probabilities by doing softmax
    probs = outputs[0].softmax(1)
    # executing argmax function to get the candidate label
    print("probs-->",probs.argmax().item(),probs.max())
    return probs.argmax().item(),probs.max()

text = """
eik sit tehdä treffit sun sängyysi ja hoidetaan yhteiset himomme pois
"""
print(get_prediction(text))

=======================

Question: Is it possible to convert in RUST? (using rust-bert)
Simple StartUp very appreciated.

**Comment by guillaume-be** [comment]
Hello @remotejob ,

Yes - multilabel classification is supported in the library. Please see the example `sequence_classification_multilabel`:
```rust

extern crate anyhow;

use rust_bert::pipelines::sequence_classification::SequenceClassificationModel;

fn main() -> anyhow::Result<()> {
    //    Set-up model
    let sequence_classification_model = SequenceClassificationModel::new(Default::default())?;

    //    Define input
    let input = [
        "Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring.",
        "This is a neutral sentence.",
        "If you like original gut wrenching laughter you will like this movie. If you are young or old then you will love this movie, hell even my mom liked it.",
    ];

    //    Run model
    let output = sequence_classification_model.predict_multilabel(&input, 0.05);
    if let Ok(labels) = output {
        for label in labels {
            println!("{:?}", label);
        }
    }

    Ok(())
}
```

Note that in your original Python code you use a `softmax` operation - you would probably want to replace that by a `sigmoid` for multilabel classification (this is what is done automatically when calling `predict_multilabel` in the Rust library.

**Comment by remotejob** [comment]
I try to use my custom model :
 https://huggingface.co/remotejob/gradientclassification_v0/

[https://gitlab.com/remotejob/gradientclassificationrust](https://gitlab.com/remotejob/gradientclassificationrust/) branch:1-start

extern crate anyhow;

use rust_bert::resources::{RemoteResource, Resource};

use rust_bert::pipelines::sequence_classification::{SequenceClassificationConfig, SequenceClassificationModel};

fn main() -> anyhow::Result<()> { 

    let custom_SequenceClassification_model = Resource::Remote(RemoteResource::new(
        
        "https://huggingface.co/remotejob/gradientclassification_v0/resolve/main/rust_model.ot",
     
        "gradientclassification_v0/model",
    ));

    let custom_SequenceClassification_vocab = Resource::Remote(RemoteResource::new(
        
        "https://huggingface.co/remotejob/gradientclassification_v0/resolve/main/vocab.txt",
     
        "gradientclassification_v0/vocab",
    ));

    let custom_SequenceClassification_config = Resource::Remote(RemoteResource::new(
        
        "https://huggingface.co/remotejob/gradientclassification_v0/resolve/main/config.json",
     
        "gradientclassification_v0/config",
    ));
    
    
    let generate_config = SequenceClassificationConfig {
        model_resource: custom_SequenceClassification_model,
        vocab_resource: custom_SequenceClassification_vocab,
        config_resource: custom_SequenceClassification_config,
        ..Default::default()
    };

    let model = SequenceClassificationModel::new(generate_config)?;

    Ok(())
}


But I have error:
could not parse configuration: Error("missing field `activation`", line: 166, column: 1)', /home/juno/repos/github.com/guillaume-be/rust-bert/src/common/config.rs:42:56

**Comment by guillaume-be** [comment]
Hello @remotejob ,

I believe you are trying to load a `Bert` model, while the default for this pipeline is `DistilBert`. Can you please try to update your configuration with
```rust
let generate_config = SequenceClassificationConfig {
    model_type: ModelType::Bert,
    model_resource: custom_SequenceClassification_model,
    vocab_resource: custom_SequenceClassification_vocab,
    config_resource: custom_SequenceClassification_config,
    ..Default::default()
};
```

**Comment by remotejob** [comment]
let output = custom_SequenceClassification_model.predict_multilabel(&input, 0.05);
                                                         ^^^^^^^^^^^^^^^^^^ method not found in `Resource`
probably it related to yours note:
"Note that in your original Python code you use a softmax operation - you would probably want to replace that by a sigmoid for multilabel classification (this is what is done automatically when calling predict_multilabel in the Rust library."?

**Comment by guillaume-be** [comment]
Hello @remotejob ,

You ened to call `predict_multilabel` on the model:
```rust
let output = model.predict_multilabel(&input, 0.05);
```
It seems you are calling this method on the model resource currently.

**Comment by remotejob** [comment]
GREEATTT!!! It was my TUPO!
Last questions:
Result clean JSON 
[Label { text: "LABEL_0", score: 0.4973698556423187, id: 0, sentence: 0 }, Label { text: "LABEL_1", score: 0.6005241870880127, id: 1, sentence: 0 }.....

Maybe exist ready-made function to find MAX score ?
{ text: "LABEL_3", score: 0.9999827146530151, id: 3, sentence: 0 }

What is a "sentence: 0"?  Always 0?

predict_multilabel(&input, 0.05) 
What for 0.05?

**Great project !!** (I am not particularly like languages starting from P.. (Python,PHP...)

Thanks.

**Comment by guillaume-be** [comment]
Hello @remotejob ,

- The `sentence` field is useful when you provide a batch of input to the function, instead of sending the sentences one by one. This would be significantly more efficient if you use a GPU. The `sentence` field then indicates the original position of the input sentence for the given label.
- The `0.05` refers to the threshold above which a label will be accepted. For multilabel prediction we do not only return the maximum score, but all predicted labels above this threshold will be considered "true". If you want only 1 label to be returned by sentence (out of possibly multiple classes), you should use the `predict` method.
- It is possible to find the highest scoring label per sentence as follows:
```rust
let output = sequence_classification_model.predict_multilabel(&input, 0.05);
if let Ok(labels) = output {
    for sequence_labels in labels {
        let max_label = sequence_labels
            .into_iter()
            .max_by(|label_a, label_b| label_a.score.partial_cmp(&label_b.score).unwrap())
            .unwrap();
        println!("{:?}", max_label);
    }
}
```
Note that it seems you are effectively trying to do multiclass classification, and should use the `predict` method if that is the case.

**Comment by remotejob** [comment]
Great all work!!
