### ISSUE TITLE
Irregular VRAM usage with gpt-neo inference with sequences longer than 250 tokens

### ISSUE THREAD

**Issue by kingpalethe** [guillaume-be/rust-bert#207]
Thanks for this great library.

I have been fighting out of memory issues with GPT-Neo interference with rust-bert, and I think I now have a clue what is going on.

Please see this issue: https://github.com/huggingface/transformers/issues/11320

I'm seeing exactly the same behavior with rust-bert -- if I input above ~250 tokens, VRAM memory use starts ballooning in unpredictable ways .... If I put in a lot of tokens, above 1000 or so, I find I can get the OOM error almost immediately.

Below 250 tokens, I am finding that VRAM usage is stable.

My rough guess is that a fix to rust-bert could be applied, copying this: https://github.com/huggingface/transformers/pull/13491

If I'm wrong about something, please feel free to close this issue.

thanks

**Comment by guillaume-be** [comment]
Hello @kingpalethe,

Thank you very much for raising this and for the investigation. This is very likely to be the same issue. I will work on a patch to reproduce the current Python's version behaviour over the next few days. I unfortunately don't have a GPU machine for testing for the next few weeks, and may reach out to you for some testing once I have a branch ready.

**Comment by kingpalethe** [comment]
Thanks, will be happy to test it when you are ready.

**Comment by guillaume-be** [comment]
@kingpalethe I have pushed some changes to the [gpt_neo_attention_fix](https://github.com/guillaume-be/rust-bert/tree/gpt_neo_attention_fix) branch.

Tests are passing and the output seems to be identical to the previous version. Could you please test if this addresses the VRAM utilization issues?

**Comment by kingpalethe** [comment]
Thanks, I added this to my `cargo.yml` like this:
`rust-bert = { git = "https://github.com/guillaume-be/rust-bert", branch = "gpt_neo_attention_fix"}`

I am using `gpt-neo-2.7B`, with `model.half();`

When the model is loaded into memory, VRAM usage is around 7100 MB.

Then I start inference.

With a `max_length` around 225 tokens, VRAM usage is stable around 7650 MB.
With a `max_length` around 500 tokens, VRAM usage is stable around 8678 MB.
With a `max_length` around 750 tokens, VRAM usage is stable around 11000 MB.
With a `max_length` around 1000 tokens, VRAM usage is stable around 13044 MB.

So yes, VRAM usage is now stable. The only way I can get it to crash is to increase the `max_length` to about 2000, likely then maxing out my GPU with 24GB VRAM.

But it does seem that with more tokens, VRAM usage goes up significantly -- maybe this is an inevitable byproduct of the way rust-bert or tch works?

I have tried some similar tests with Python transformers, and I'm finding that VRAM usage in python transformers does not seem to scale up as fast.

With python transformers...
With a `max_length` around 250 tokens, VRAM usage is stable around 6842 MB.
With a `max_length` around 1000 tokens, VRAM usage is stable around 7500 MB.

(With higher numbers of tokens, python transformers get slower and slower in comparison to rust-bert)

**Comment by guillaume-be** [comment]
Hello @kingpalethe,

Thank you for validating that the memory footprint is now more stable. The backend used by the Python transformers and the Rust version is the same and there should be no reason the memory use is larger in Rust. I will look for a potential difference on how the half precision or internal calculations are handled between these options.

Could you please verify that the generations options are identical between the Python and Rust versions? The following may impact the memory use significantly:
- Number of beams for generation
- Minimum and maximum length for the generation
- Tokenizer maximum length, potentially truncating the input before it is passed for generation
- both models cast to half precision

Is the output of both the Python model and Rust model equivalent for a given length?

**Comment by kingpalethe** [comment]
Thanks, after some extensive testing, making sure to keep all the options and inputs consistent, I'm not able to show that rust-bert VRAM memory usage is higher. And with this branch the runaway memory behavior has never happened either. Thanks... closing this.

**Comment by guillaume-be** [comment]
Great - thanks again for raising this and finding the root cause!
