### ISSUE TITLE
Zero shot classification and slot filling?

### ISSUE THREAD

**Issue by jackpeters667** [guillaume-be/rust-bert#214]
Hi there, this looks like an awesome project. I'm looking for a way to achieve what the title describes, basically.
Something like `Remind me to send an email to person about code review at time`. 
So something with Named-entity recognition and Intent classification perhaps. 

What would I have to do?

**Comment by guillaume-be** [comment]
Hello @jackpeters667 ,

The library already offers model and pipeline capabilities for both zero-shot classification and named entity recognition. 

- For zero-shot classification, I invite you to check the example at https://github.com/guillaume-be/rust-bert/blob/master/examples/zero_shot_classification.rs. You would probably be able to provide a list of intents you would like to capture and get good results using the existing default model. The pipeline in general would accept any model that was trained for natural language inference, and you may get better results using a larger or more modern model that was trained on a reference benchmark dataset such as MNLI or RTE. Models on the [Huggingface model hub](https://huggingface.co/models?pipeline_tag=text-classification&sort=downloads&search=nli) should be compatible provided the architecture is supported in `rust-bert` and after conversion of the weights to the `ot` format (see https://github.com/guillaume-be/rust-bert/blob/master/utils/convert_model.py)
- Named entity recognition is demonstrated in https://github.com/guillaume-be/rust-bert/blob/master/examples/named_entities_recognition.rs. Similarly to NLI, any pytorch checkpoint compatible with Huggingface's Transformers library can be converted and loaded in this Rust implementation provided the architecture is supported. You would probably have to train your own NER model to extract the entities relevant for your slot filling application, I would recommend leveraging the rich Python ecosystem for training these models (although the models support training mode, you would have to write your data loaders, training loop and utilities in Rust)

I hope this helps

**Comment by jackpeters667** [comment]
Ahh thanks for getting back to me. I'm actually porting over a python project I had (enjoying Rust more) and I already have an NER model in python, but it's a .pth. Will `convert_model.py` help in converting it to `.ot`

**Comment by jackpeters667** [comment]
I'm trying the `convert_model.py` script on my `pth` model now and im receiving this:
```python
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:604: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  " silence this warning)", UserWarning)
Traceback (most recent call last):
  File "convert_model.py", line 22, in <module>
    for k, v in weights.items():
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 757, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 474, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'RecursiveScriptModule' object has no attribute 'items'
```

**Comment by jackpeters667** [comment]
Okay just an update. I changed this [line](https://github.com/guillaume-be/rust-bert/blob/a7a39ff9435540c75afcdd004dc1b289a28e7b82/utils/convert_model.py#L19) to 
`py
 weights = torch.load(str(source_file), map_location='cpu').state_dict()
`
And the conversion worked. However, when I try to use the model in rust, I get

```
thread 'main' panicked at 'num_labels not provided in configuration', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.17.0/src/bert/bert_model.rs:919:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm using a fine-tuned `bert-base-uncased` model. And I have loaded custom resources.
```rust
    let model_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("rust_model.ot"),
    });
    let config_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("config.json"),
    });
    let vocab_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("vocab.txt"),
    });
    let token = TokenClassificationConfig {
        model_type: rust_bert::pipelines::common::ModelType::Bert,
        model_resource,
        config_resource,
        vocab_resource,
        lower_case: true,
        ..Default::default()
    };

    let model = NERModel::new(token).unwrap();
    let input = ["My name is Amy. I live in Paris."];
    let output = model.predict(&input);

```
I got the other resources from [here](https://huggingface.co/bert-base-uncased/tree/main)
Any pointers?

**Comment by guillaume-be** [comment]
Hello @jackpeters667 ,

First of all - my apologies for not getting back to you earlier. I am glad you could convert your Pytorch weights to C-arrays.
Regarding your second issue, this is because you are attempting to use a token classification model without specifying the label mapping. The model configuration need to provide a mapping from label ID to class label. This is typically absent from MLM model checkpoints.

Please see for example https://huggingface.co/dslim/bert-base-NER/blob/main/config.json: the field `id2label` need to be included (for example):
```json
  "id2label": {
    "0": "O",
    "1": "B-MISC",
    "2": "I-MISC",
    "3": "B-PER",
    "4": "I-PER",
    "5": "B-ORG",
    "6": "I-ORG",
    "7": "B-LOC",
    "8": "I-LOC"
  },
```

You'll need to replace this mapping with the id->label information from your own pre-trained model.

**Comment by jackpeters667** [comment]
@guillaume-be no worries, you're probably busy with other things :) . I appreciate the time you're making for us! And I think i understand it now. I thank you, I'll close this now since we're all sorted
