### ISSUE TITLE
Including models at build time?

### ISSUE THREAD

**Issue by Calandiel** [guillaume-be/rust-bert#215]
Hello, I'm looking for a way to include the model at build time (perhaps through a build.rs script) with the executable that uses rust-bert.
I really don't want to overuse hugginface's bandwidth (or rely on their servers having 100% uptime...).
I poked around a bit and it looks like it's not really supported currently. Is that the correct assessment?

With regards,
Cal

**Comment by guillaume-be** [comment]
Hello @Calandiel ,

The library currently supports 2 types of `Resource` model objects:
- [RemoteResources](https://docs.rs/rust-bert/0.17.0/rust_bert/resources/struct.RemoteResource.html) that point to a model repository and allow local caching of the files (including a version check with the remote and re-download when necessary)
- [LocalResource](https://docs.rs/rust-bert/0.17.0/rust_bert/resources/struct.LocalResource.html) that point to a model on the local file system. [Here](https://github.com/guillaume-be/rust-bert/blob/d6e6ed097b6e4a124b8f0897815228cbf619d69e/tests/reformer.rs#L34) is an example of how it is used in the tests to point to a config object serialized on the fly.

This would support including the file alongside the executable and load it without accessing any remote server. If you want to include the file at build time using for example `include_bytes!`, we could add a 3rd type of resource that would just point to an array of bytes.

**Comment by Calandiel** [comment]
Ah,`LocalResource` seems to be what I was looking for, thank you ^^
