### ISSUE TITLE
Basic command line example use?

### ISSUE THREAD

**Issue by rlabs-oss** [guillaume-be/rust-bert#218]
how do I build / run the examples?

rustc examples/generation_gpt_neo.rs 
error[E0463]: can't find crate for `anyhow`
  --> examples/generation_gpt_neo.rs:15:1
   |
15 | extern crate anyhow;
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.

**Comment by guillaume-be** [comment]
Hello @rlabs-oss ,

I recommend using _cargo_: 
`cargo run --example generation_gpt_neo`

This should build the project, install the required dependencies and run the example. Please let me know if this works for you.

**Comment by rlabs-oss** [comment]
Thank you, "it works" :)

cargo run --example generation_gpt_neo
  Downloaded criterion-plot v0.4.4
  Downloaded serde_cbor v0.11.2
  Downloaded criterion v0.3.5
  Downloaded plotters-svg v0.3.1
  Downloaded plotters-backend v0.3.2
  Downloaded oorandom v11.1.3
  Downloaded tinytemplate v1.2.1
  Downloaded textwrap v0.11.0
  Downloaded rustc_version v0.4.0
  Downloaded atty v0.2.14
  Downloaded cast v0.2.7
  Downloaded same-file v1.0.6
  Downloaded clap v2.34.0
  Downloaded walkdir v2.3.2
  Downloaded semver v1.0.4
  Downloaded plotters v0.3.1
  Downloaded 16 crates (9.1 MB) in 1.39s (largest was `plotters` at 8.6 MB)
   Compiling semver v1.0.4
   Compiling plotters-backend v0.3.2
   Compiling same-file v1.0.6
   Compiling oorandom v11.1.3
   Compiling textwrap v0.11.0
   Compiling atty v0.2.14
   Compiling serde_cbor v0.11.2
   Compiling tinytemplate v1.2.1
   Compiling walkdir v2.3.2
   Compiling clap v2.34.0
   Compiling plotters-svg v0.3.1
   Compiling plotters v0.3.1
   Compiling rustc_version v0.4.0
   Compiling cast v0.2.7
   Compiling criterion-plot v0.4.4
   Compiling criterion v0.3.5
   Compiling rust-bert v0.17.0 (/home/lab/external-source/rust-bert)
    Finished dev [unoptimized + debuginfo] target(s) in 21.60s
     Running `target/debug/examples/generation_gpt_neo`
Downloading https://huggingface.co/EleutherAI/gpt-neo-125M/resolve/main/config.json [1007B]... ✓ Done! Finished in 0 seconds
Downloading https://huggingface.co/EleutherAI/gpt-neo-125M/resolve/main/vocab.json [877.61KB]... ✓ Done! Finished in 0 seconds
Downloading https://huggingface.co/EleutherAI/gpt-neo-125M/resolve/main/merges.txt [445.62KB]... ✓ Done! Finished in 0 seconds
Downloading https://huggingface.co/EleutherAI/gpt-neo-125M/resolve/main/rust_model.ot [501.65MB]........ ✓ Done! Finished in 48 seconds
It was a very nice and sunny day. The sun was shining through the clouds, and the sky was clear. The wind was blowing through the trees,
It was a gloom winter night, and the sky was dark and cold, and the wind was blowing thick and heavy.

"What's the matter?"
