### ISSUE TITLE
Multi-threaded model execution

### ISSUE THREAD

**Issue by FlixCoder** [guillaume-be/rust-bert#220]
Hi!

I have noticed that the models (e.g. `SentimentModel`) execute on a single thread only on CPU (using libtorch_cpu). Is it possible to somehow use multiple CPU cores with [`set_num_threads`](https://docs.rs/torch-sys/0.6.1/torch_sys/fn.at_set_num_threads.html)?

**Comment by guillaume-be** [comment]
Hello @FlixCoder ,

As far as I know the CPU execution defaults to 1 thread per available core. I tested briefly and running a large model on CPU seems to effectively use all 8 of my CPU: 
![resources](https://user-images.githubusercontent.com/27071604/153756434-bd44e3d9-e79a-432b-b937-4f302602b5a3.png)

If you would like to increase the number of threads used for parallel computation I believe the unsafe method you linked to is exposed at the `tch` level via [set_num_threads](https://github.com/LaurentMazare/tch-rs/blob/406145227d0750625a7e3f7a02f3a9f91e70cb75/src/lib.rs#L17) which is probably a better alternative. 

Can you try to use this method via 
```rust
tch::set_num_threads(NUM_THREADS);
```
before loading and running the models?

**Comment by FlixCoder** [comment]
Oh right, `tch` is better, thanks.

I didn't know it is per core level and not per-thread level, that could actually explain it. I thought the second core would be the rest my application, but then it might be libtorch using my 2 cores instead of 4 threads. ^^ I was wondering why it didn't do 100% CPU usage.

Thank you, everything fine then!
