### ISSUE TITLE
GPT2 model for T5Tokenizer does not work.

### ISSUE THREAD

**Issue by ycat3** [guillaume-be/rust-bert#221]
GPT2 1.3B,  A 24-layer, 2048-hidden-size transformer-based language model
vocabulary resource file is spiece.model

I have converted pytorch_model.bin to rust_model.ot successfully.
I modified an examples/summarization_t5.rs file as testing template.
---------------------------------------------------------------------------------------------------
Error: Tokenizer error: Error when loading vocabulary file, the file may be corrupted or does not match the expected format: unexpected wire type
-------------------------------------------------------------------------------------------------------------------------------------------
When I use python, it works fine.
For example.
-------------------------------------------------------------------------------------------------------------------
import torch
from transformers import T5Tokenizer, AutoModelForCausalLM

tokenizer = T5Tokenizer.from_pretrained("rinna/japanese-gpt-1b")
model = AutoModelForCausalLM.from_pretrained("rinna/japanese-gpt-1b")
#model = GPT2LMHeadModel.from_pretrained("rinna/japanese-gpt-1b")

if torch.cuda.is_available():
    model = model.to("cuda")

text = "夏目漱石は、"
token_ids = tokenizer.encode(text, add_special_tokens=False, return_tensors="pt")
with torch.no_grad():
    output_ids = model.generate(
        token_ids.to(model.device),
        max_length=100,
        min_length=100,
        do_sample=True,
        top_k=500,
        top_p=0.95,
        pad_token_id=tokenizer.pad_token_id,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
        bad_word_ids=[[tokenizer.unk_token_id]]
    )

output = tokenizer.decode(output_ids.tolist()[0])
print(output)  
--------------------------------------------------------------------------------------------------------------------
Not yet implemented for this purpose and feature ?

**Comment by guillaume-be** [comment]
Hello @ycat3 ,

Could you please share the Rust code that is not working? I just tried the following on my end and cannot reproduce the error:
```rust
use rust_bert::resources::{RemoteResource, Resource};
use rust_tokenizers::tokenizer::T5Tokenizer;

fn main() -> anyhow::Result<()> {
    let vocab_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/rinna/japanese-gpt-1b/resolve/main/spiece.model".into(),
        cache_subdir: "japanese-gpt-1b/vocab".into(),
    });
    let vocab_path = vocab_resource.get_local_path()?;

    let _tokenizer = T5Tokenizer::from_file(vocab_path.to_str().unwrap(), false)?;

    Ok(())
}
```

I go get a different error though, indicating that the vocabulary does not contain the unknown token:
```
Error: Token not found in vocabulary: The special value <unk> could not be found in the vocabulary
```

**Comment by ycat3** [comment]
Error: Token not found in vocabulary: The special value <unk> could not be found in the vocabulary
Yes, I encounters this error at last and the error is strange.
The following code shows sentence_piece_model.common_prefix_search works.
However T5Tokenizer error always happens.
------------------------------------------------------------------------------------
use rust_bert::resources::{RemoteResource, Resource};
use rust_tokenizers::tokenizer::T5Tokenizer;
use rust_tokenizers::vocab::{ T5Vocab, Vocab, SentencePieceModel};

fn main() -> anyhow::Result<()> {
    let vocab_resource = Resource::Remote(RemoteResource {
        url: "https://huggingface.co/rinna/japanese-gpt-1b/resolve/main/spiece.model".into(),
        cache_subdir: "japanese-gpt-1b/vocab".into(),
    });
    let vocab_path = vocab_resource.get_local_path()?;
    let sentence_piece_model = SentencePieceModel::from_file(&vocab_path.to_str().unwrap())?;
    let input_context = "今日は雪になりそうだ。";
    let output = sentence_piece_model.common_prefix_search(input_context);
    for sentence in output {
        println!("{:?}", sentence);
    }    
   // let _tokenizer = T5Tokenizer::from_file(vocab_path.to_str().unwrap(), true)?;
    Ok(())
}

**Comment by ycat3** [comment]
When I use my converted rust_model.ot
Error: Tokenizer error: Error when loading vocabulary file, the file may be corrupted or does not match the expected format: unexpected wire type
----------------------------------------------------------------------------------------------------------------------------------
extern crate anyhow;
use std::path::PathBuf;
use rust_bert::pipelines::common::ModelType;
use rust_bert::pipelines::summarization::{SummarizationConfig, SummarizationModel};
use rust_bert::resources::{RemoteResource, LocalResource, Resource};
fn main() -> anyhow::Result<()> {
    let config_resource =
        Resource::Remote(RemoteResource::from_pretrained((
        "rinna/japanese-gpt-1b",
       "https://huggingface.co/rinna/japanese-gpt-1b/blob/main/config.json")));
    
    let vocab_resource =
        Resource::Remote(RemoteResource::from_pretrained((
         "rinna/japanese-gpt-1b",
       "https://huggingface.co/rinna/japanese-gpt-1b/blob/main/spiece.model")));
    let weights_resource =Resource::Local(LocalResource{
       // Resource::Remote(RemoteResource::from_pretrained(T5ModelResources::T5_SMALL));
       local_path: PathBuf::from("/myconverted/rust_model.ot"),
       });
   
    let summarization_config = SummarizationConfig::new(
        ModelType::T5,
        weights_resource,
        config_resource,
        vocab_resource.clone(),
        vocab_resource,
    );
    let summarization_model = SummarizationModel::new(summarization_config)?;
    let input = ["In findings published Tuesday in Cornell University's arXiv by a team of scientists"];

    let _output = summarization_model.summarize(&input);
    for sentence in _output {
        println!("{}", sentence);
    }

    Ok(())
}

**Comment by guillaume-be** [comment]
The issue is not related to `model.ot`: you have the wrong path for the tokenizer file. Your current URL points to a HTML file and does not contain the model itself. You should replace `https://huggingface.co/rinna/japanese-gpt-1b/blob/main/spiece.model` by `https://huggingface.co/rinna/japanese-gpt-1b/resolve/main/spiece.model` to download the actual file.

This will download the tokenizer file but will still fail because of the issue mentioned above (the T5 tokenizer expects the vocabulary to contain a `<unk>` and `<pad>` tokens). I just tried a workaround that seems to work:
1. Download the vocabulary file at https://huggingface.co/rinna/japanese-gpt-1b/resolve/main/spiece.model
2. Manually update the vocabulary to set the special values in the vocabulary to their expected value. The following code snippet would do that for you (update the source and target file, you need to be in a virtual environment with `sentencepiece` installed):
```python
from sentencepiece import sentencepiece_model_pb2 as model
m = model.ModelProto()
m.ParseFromString(open('spiece.model', 'rb').read())
m.pieces[0].piece = '<cls>'
m.pieces[1].piece = '<unk>'
m.pieces[4].piece = '<pad>'
m.pieces[5].piece = '<sep>'
m.pieces[6].piece = '<mask>'

with open('updated_spiece.model', 'wb') as f:
    f.write(m.SerializeToString())
```
3. Load the updated vocabulary file:
```rust
fn main() -> anyhow::Result<()> {
    let vocab_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("E:/Coding/notebooks/updated_spiece.model"),
    });
    let vocab_path = vocab_resource.get_local_path()?;

    let _tokenizer = T5Tokenizer::from_file(vocab_path.to_str().unwrap(), false)?;

    Ok(())
}

```

**Comment by ycat3** [comment]
Thanks a lot.
T5Tokenizer works fine.
I would like to know how to use T5Tokenizer when generating inference output such as in python transformers.
---------------------------------------------------------------------------------------------------------------------
tokenizer = T5Tokenizer.from_pretrained("rinna/japanese-gpt-1b")
model = GPT2LMHeadModel.from_pretrained("rinna/japanese-gpt-1b")
token_ids = tokenizer.encode(text, add_special_tokens=False, return_tensors="pt")

with torch.no_grad():
    output_ids = model.generate(
        token_ids.to(model.device),
        max_length=100,
        min_length=100,
        do_sample=True,
        top_k=500,
        top_p=0.95,
        pad_token_id=tokenizer.pad_token_id,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
        bad_word_ids=[[tokenizer.unk_token_id]]
    )

output = tokenizer.decode(output_ids.tolist()[0])
---------------------------------------------------------------------------------------------------
In rust
---------------------------------------------------------------------------------------------------
fn main() -> anyhow::Result<()> {
    let vocab_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("E:/Coding/notebooks/updated_spiece.model"),
    });
    let vocab_path = vocab_resource.get_local_path()?;

    let _tokenizer = T5Tokenizer::from_file(vocab_path.to_str().unwrap(), false)?;
    let generate_config = TextGenerationConfig {
        model_type: ModelType::GPT2,
        max_length: 60,
        do_sample: true,
        num_beams: 1,
        temperature: 1.0,
        num_return_sequences: 1,
        ..Default::default()
    };
    let model = TextGenerationModel::new(generate_config)?;
    let input_context = "夏目漱石は、";
　let output_ids = model.generate(&[input_context], None);
　let output = tokenizer.decode(&output_ids[0], true, true);
    Ok(())
}
---------------------------------------------------------------------------------------------------
output_ids is already Vec<string>
The above code build failed.

**Comment by guillaume-be** [comment]
The `TextGenerationModel` will automatically load an build matching models/tokenizer (GPT2 in this case) making it inappropriate for this use case since you want to encode your input with a tokenizer that does not match the model default. You would need to use the lower-level API [LanguageGenerator](https://docs.rs/rust-bert/latest/rust_bert/pipelines/generation_utils/trait.LanguageGenerator.html) allowing you to trigger a generation directly from  an encoded input using a `GPT2Generator`. Since the `Generator` models also create their tokenizer on the fly, the `GPT2Generator` needs to get a valid GPT2 vocab/merges - even if we don't plan on using this tokenizer (these are the "dummy" vocab and merges below). This may cause some issues if the special token values (e.g. `pad` and `eos`) differ from the T5Tokenizer you want to create. I could extend the `Generator` objects to allow creating them from an existing tokenizer, which would significantly simplify the code below.

The code bellow illustrates this approach, which becomes similar to the Python code you provided:

```rust
use rust_bert::gpt2::{GPT2Generator, Gpt2MergesResources, Gpt2VocabResources};
use rust_bert::pipelines::generation_utils::{GenerateConfig, LanguageGenerator};
use rust_bert::resources::{LocalResource, RemoteResource, Resource};
use rust_tokenizers::tokenizer::{T5Tokenizer, Tokenizer, TruncationStrategy};
use std::path::PathBuf;
use tch::{Device, Tensor};

fn main() -> anyhow::Result<()> {
    let model_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("path/to/model.ot"),
    });
    let config_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("path/to/config.json"),
    });
    let dummy_gpt2_vocab_resource =
        Resource::Remote(RemoteResource::from_pretrained(Gpt2VocabResources::GPT2));
    let dummy_gpt2_merges_resource =
        Resource::Remote(RemoteResource::from_pretrained(Gpt2MergesResources::GPT2));
    let vocab_resource = Resource::Local(LocalResource {
        local_path: PathBuf::from("path/to/updated_spiece.model"),
    });

    let generate_config = GenerateConfig {
        model_resource,
        config_resource,
        vocab_resource: dummy_gpt2_vocab_resource,
        merges_resource: dummy_gpt2_merges_resource,
        device: Device::cuda_if_available(),
        ..Default::default()
    };

    let gpt2_model = GPT2Generator::new(generate_config)?;
    let tokenizer = T5Tokenizer::from_file(
        vocab_resource.get_local_path().unwrap().to_str().unwrap(),
        false,
    )?;

    let input_text = "Some text here";
    let encoded_input =
        tokenizer.encode(input_text, None, 512, &TruncationStrategy::DoNotTruncate, 0);
    let input_tensor =
        Tensor::of_slice(encoded_input.token_ids.as_slice()).to_device(Device::cuda_if_available());

    let model_output = gpt2_model.generate_from_ids_and_past(input_tensor, None, None);
    let output = tokenizer.decode(model_output[0].indices.as_slice(), true, true);
    println!("{}", output);

    Ok(())
}

```

Can you please give this a try, and I will work on an extension allowing passing tokenizers to `Generator` objects for these use cases.

**Comment by ycat3** [comment]
Thank you.
Build passed, however runtime error.
Torch tensor mismatch.
Libtorch 1.10.2
------------------------------------------------------------------------------
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("The expanded size of the tensor (5) must match the existing size (8) at non-singleton dimension 1.  Target sizes: [8, 5, 8].  Tensor sizes: [8, 1]\nException raised from inferExpandGeometryImpl at ../aten/src/ATen/ExpandUtils.cpp:91 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f7b79c4d0db in /home/mycat/libtorch/lib/libc10.so)\nframe #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xce (0x7f7b79c48d2e in /home/mycat/libtorch/lib/libc10.so)\nframe #2: at::inferExpandGeometry_dimvector(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>) + 0x31c (0x7f7b7b054f5c in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #3: at::native::expand(at::Tensor const&, c10::ArrayRef<long>, bool) + 0x8f (0x7f7b7b54764f in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #4: <unknown function> + 0x1f24fbc (0x7f7b7bdb1fbc in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #5: at::_ops::expand::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>, bool) + 0xde (0x7f7b7baea1ae in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #6: <unknown function> + 0x3aa1ed7 (0x7f7b7d92eed7 in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #7: <unknown function> + 0x3aa226f (0x7f7b7d92f26f in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #8: at::_ops::expand::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>, bool) + 0xde (0x7f7b7baea1ae in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #9: <unknown function> + 0x365d6ac (0x7f7b7d4ea6ac in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #10: <unknown function> + 0x365dc6f (0x7f7b7d4eac6f in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #11: at::_ops::expand::call(at::Tensor const&, c10::ArrayRef<long>, bool) + 0x161 (0x7f7b7bb07101 in /home/mycat/libtorch/lib/libtorch_cpu.so)\nframe #12: <unknown function> + 0xbfb281 (0x55b2214fa281 in target/debug/examples/GPT2_T5)\nframe #13: <unknown function> + 0xc04e3c (0x55b221503e3c in target/debug/examples/GPT2_T5)\nframe #14: <unknown function> + 0xb8f993 (0x55b22148e993 in target/debug/examples/GPT2_T5)\nframe #15: <unknown function> + 0xb95670 (0x55b221494670 in target/debug/examples/GPT2_T5)\nframe #16: <unknown function> + 0x1cbd61 (0x55b220acad61 in target/debug/examples/GPT2_T5)\nframe #17: <unknown function> + 0x1aa698 (0x55b220aa9698 in target/debug/examples/GPT2_T5)\nframe #18: <unknown function> + 0x1a91cb (0x55b220aa81cb in target/debug/examples/GPT2_T5)\nframe #19: <unknown function> + 0x1a8e4e (0x55b220aa7e4e in target/debug/examples/GPT2_T5)\nframe #20: <unknown function> + 0x1a93e1 (0x55b220aa83e1 in target/debug/examples/GPT2_T5)\nframe #21: <unknown function> + 0xc793db (0x55b2215783db in target/debug/examples/GPT2_T5)\nframe #22: <unknown function> + 0x1a93b0 (0x55b220aa83b0 in target/debug/examples/GPT2_T5)\nframe #23: <unknown function> + 0x1aa9cc (0x55b220aa99cc in target/debug/examples/GPT2_T5)\nframe #24: <unknown function> + 0x2dfd0 (0x7f7b798d3fd0 in /lib/x86_64-linux-gnu/libc.so.6)\nframe #25: __libc_start_main + 0x7d (0x7f7b798d407d in /lib/x86_64-linux-gnu/libc.so.6)\nframe #26: <unknown function> + 0x1a88d5 (0x55b220aa78d5 in target/debug/examples/GPT2_T5)\n")', /home/mycat/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.6.1/src/wrappers/tensor_generated.rs:4533:39

stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: tch::wrappers::tensor_generated::<impl tch::wrappers::tensor::Tensor>::expand
             at /home/mycat/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.6.1/src/wrappers/tensor_generated.rs:4533:9
   5: rust_bert::pipelines::generation_utils::LanguageGenerator::generate_from_ids_and_past
             at ./src/pipelines/generation_utils.rs:1839:21
   6: GPT2_T5::main
             at ./examples/GPT2_T5.rs:94:24
   7: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
--------------------------------------------------------------------------------------------------------------------------------
I have modified config.json to adapt compiler request.
However I don't think the serious problem.
config.json:
----------------------------------------------------------------------------------
{
  "activation_function": "gelu_fast",
  "architectures": [
    "GPT2LMHeadModel"
  ],
// Added
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    },
    "summarization": {
     "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
    "translation_en_to_de": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to German: "
    },
    "translation_en_to_fr": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to French: "
    },
    "translation_en_to_ro": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to Romanian: "
    }
  },
  "relative_attention_num_buckets":32,
  "num_beams":4,
  "num_layers":24, 
  "num_heads":16,
  "initializer_factor": 1.0, 
  "d_kv":64, 
  "d_ff": 4096,
  "d_model": 768, 
  "dropout_rate": 0.1,
  // End Added
  "attn_pdrop": 0.1,
  "bos_token_id": 2,
  "embd_pdrop": 0.1,
  "eos_token_id": 3,
  "gradient_checkpointing": false,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 2048,
  "n_head": 16,
  "n_inner": 8192,
  "n_layer": 24,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "use_cache": true,
  "vocab_size": 44928
}
---------------------------------------------------------------------------------------------------------

**Comment by guillaume-be** [comment]
Hello @ycat3 

My mistake - the input tensor needs an additional dimension. Can you try replacing 
```rust
    let input_tensor =
        Tensor::of_slice(encoded_input.token_ids.as_slice()).to_device(Device::cuda_if_available());
```
with
```rust
    let input_tensor =
        Tensor::of_slice(encoded_input.token_ids.as_slice()).to_device(Device::cuda_if_available()).unsqueeze(0);
```

**Comment by ycat3** [comment]
Thank you.
It works fine.
There are small problems.
1. Cuda usage is higher than python transformers.
I am using a 11GB cuda card, however  Cuda out of memory happens.
2. Setting min_length:40 causes "Torch("index 50256 is out of bounds for dimension 1".
-------------------------------------------------------------------------------------------------------
//let device = Device::cuda_if_available();    
    let device = Device::Cpu;
    let generate_config = GenerateConfig {
        model_resource,
        config_resource,
        vocab_resource: dummy_gpt2_vocab_resource,
        merges_resource: dummy_gpt2_merges_resource,
        device: device,
        repetition_penalty: 1.5,//default 1.0,
        min_length: 10,//40,
        max_length: 200, 
        do_sample: true,
        early_stopping: true,
        num_beams: 1,// default 5
        temperature: 1.0,
        top_k: 500,
        top_p: 0.95,
        ..Default::default()
    };
--------------------------------------------------------------------------------------------------------

**Comment by guillaume-be** [comment]
Hello @ycat3 ,

For the first point, this could be because the Pytorch version uses half precision parameters for the model. Can you please try to update the code to load the model onto memory, convert to half-precision and then move to the GPU buffer? Please see the code snippet below:

```rust
let generate_config = GenerateConfig {
    model_resource,
    config_resource,
    vocab_resource: dummy_gpt2_vocab_resource,
    merges_resource: dummy_gpt2_merges_resource,
    device: Device::Cpu,
    ..Default::default()
};

let mut gpt2_model = GPT2Generator::new(generate_config)?;
gpt2_model.half();
gpt2_model.set_device(Device::cuda_if_available());
```

Regarding the second point, this is indeed a drawback of the workaround mentioned as the generation routine still relies on the GPT2 tokenizer and vocab to get the EOS token id. I will push a pull request in the next few days allowing to combine generators with other tokenizers that would solve the issue and greatly simplify the process.

**Comment by ycat3** [comment]
Thank you guillaume.

I have already tried half model before.
I realized device: Device::Cpu, is important when setting generate_config.
Now both cuda full and half model are working.
------------------------------------------------------------------------------------------------------
    let generate_config = GenerateConfig {
    model_resource,
    config_resource,
    vocab_resource: dummy_gpt2_vocab_resource,
    merges_resource: dummy_gpt2_merges_resource,
//  device::Device::cuda_if_available,
    device: Device::Cpu,
    ..Default::default()
};

**Comment by guillaume-be** [comment]
Hello @ycat3 ,

I have pushed some changes allowing using a different tokenizer than the default for `Generators`. You can try this out on the [flexible_tokenizer_generator branch](https://github.com/guillaume-be/rust-bert/tree/flexible_tokenizer_generator). This greatly simplifies the set-up and should fix the special token indices that were causing OOV errors previously. Feel free to have a look and let me know what you think.

```rust
use rust_bert::gpt2::GPT2Generator;
use rust_bert::pipelines::common::{ModelType, TokenizerOption};
use rust_bert::pipelines::generation_utils::{GenerateConfig, LanguageGenerator};
use rust_bert::resources::{LocalResource, ResourceProvider};
use std::path::PathBuf;
use tch::Device;

fn main() -> anyhow::Result<()> {
    let model_resource = LocalResource {
        local_path: PathBuf::from("path/to/model.ot"),
    };
    let config_resource = LocalResource {
        local_path: PathBuf::from("path/to/config.json"),
    };
    let vocab_resource = LocalResource {
        local_path: PathBuf::from("path/to/updated_spiece.model"),
    };

    let generate_config = GenerateConfig {
        model_resource: Box::new(model_resource),
        config_resource: Box::new(config_resource),
        vocab_resource: Box::new(vocab_resource.clone()), // unused
        merges_resource: Box::new(vocab_resource.clone()), // unused
        device: Device::cuda_if_available(),
        ..Default::default()
    };
    let tokenizer = TokenizerOption::from_file(
        ModelType::T5,
        vocab_resource.get_local_path().unwrap().to_str().unwrap(),
        None,
        false,
        None,
        None,
    )?;
    let gpt2_model = GPT2Generator::new_with_tokenizer(generate_config, tokenizer.into())?;

    let input_text = "Some text here";
    let output = gpt2_model.generate(Some(&[input_text]), None);
    println!("{}", output[0].text);

    Ok(())
}

```

**Comment by ycat3** [comment]
Basically, it worked fine.
Thank you guillaume.
