### ISSUE TITLE
[Question] How to load custom models?

### ISSUE THREAD

**Issue by liebkne** [guillaume-be/rust-bert#227]
Hi, thanks for the great library. Not really an issue of `rust-bert`. I'm wondering how to load custom model built top of transformers models?

For example, a model uses `BertModel` as an encoder and forwards encoded outputs to a `LSTM` and finally projects the last hidden states using a `nn.Linear`, do I need to write the Rust model counterpart like `BertForSequenceClassification` in `bert/bert_model.rs` using `tch` (also matching the model field names) and use `utils/convert_model.py` to convert model saved in Python using `torch.jit.save`?

Thanks!

**Comment by guillaume-be** [comment]
Hello @liebkne ,

This is correct - that would be the way to implement this (very similar to how you would do it in Python). You need to implement the custom module (in Rust as a `Struct`/`impl` block pair) that would have a `self.bert_model` base and a few additional modules such as `LSTM`.

The naming of the fields for the struct do not matter (as opposed to Pytorch) - you need to match the name of the Python parameters when you register the tensor in the `Varstore`. For example, assuming you have the following Python module:
```python
class MyModel(nn.Module):
    def __init__(self):
        self.dense_a = nn.Linear(config.hidden_size, config.hidden_size)
        self.another_component = nn.Linear(config.hidden_size, config.hidden_size)
```

The Rust implementation could be:
```rust
struct MyRustModel {
    dense_xyz: nn::Linear
    whatever_name: nn::Linear
}

impl MyRustModel {
    pub fn new<'p, P>(p: P, config: Config) -> MyRustModel 
    where
        P: Borrow<nn::Path<'p>>,
    {
        dense_xyz = nn::linear(p / "dense_a", config.hidden_size, config.hidden_size, Default::default())
        whatever_name= nn::linear(p / "another_component", config.hidden_size, config.hidden_size, Default::default())
        MyRustModel  {dense_xyz, whatever_name}
    }
}
```

The `convert_model.py` could indeed be used to convert a Pytorch **parameters dictionary** (and not a compiled jit model). You would need to save the model with `torch.save(model.state_dict(), output_file)`. The [tch](https://github.com/LaurentMazare/tch-rs) crate allows loading compiled jit model and may be easier to use if you wish to use these.

**Comment by liebkne** [comment]
@guillaume-be 

Hi, that helps a lot! Thanks!.

But I'm not fully understand the `convert_model.py` part. Are the `rust_model.ot`s on the hub saved by `torch.save` and postprocessed by `convert_model.py`? Also, I've thought `tch` can only load [jit](https://github.com/LaurentMazare/tch-rs/tree/main/examples/jit) models and so does `rust-bert` as it built upon `tch`. What am I missing?

**Comment by guillaume-be** [comment]
Hi @liebkne ,

`rust-bert` is indeed built on top of `tch`, but `tch` allows loading models from both parameters state dictionaries and from compiled jit binaries. 
- Loading jit compiled scripts does not require specifying the underlying architecture: an example is provided in https://github.com/LaurentMazare/tch-rs/tree/main/examples/jit. You may be able to reload your compiled model directly without using this crate.
- Loading a parameter state dictionary (`.ot` file) requires to specify the architecture to load the weights into. This is illustrated in https://github.com/LaurentMazare/tch-rs/blob/main/examples/pretrained-models/main.rs

No conversion is required to load a torchscript file from Python to Rust - the `convert_model.py` is useful only for the second scenario described above.

**Comment by liebkne** [comment]
Hi @guillaume-be , that's helpful. Thanks for the detail explanation!
