### ISSUE TITLE
the trait `ResourceProvider` is not implemented for `Box<RemoteResource>

### ISSUE THREAD

**Issue by ycat3** [guillaume-be/rust-bert#229]
Hello Guillaume-be,
You are going to update to Box::new().
However it seem to be ResourceProvider trait for RemoteResource is not well implemented.
It works with LocalResource.
----------------------------------------------------------------------------------------------------------------------
let config_resource = Box::new(RemoteResource {
        url: "https://huggingface.co/rinna/japanese-gpt-1b/resolve/main/config.json".into(),
        cache_subdir: "japanese-gpt-1b/config".into(),
 });
let generate_config = GenerateConfig {    
     config_resource: Box::new(config_resource),
};
-----------------------------------------------------------------------------------------------------
config_resource: Box::new(config_resource),
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ResourceProvider` is not implemented for `Box<RemoteResource>`
   |
   = note: required for the cast to the object type `dyn ResourceProvider + Send`

**Comment by guillaume-be** [comment]
Hello @ycat3 

It looks like you are wrapping the `RemoteResource` twice in a config. The following compiles file by removing one of these `Box::new` calls:
```rust
fn main() -> anyhow::Result<()> {
    let config_resource = Box::new(RemoteResource {
        url: "https://huggingface.co/rinna/japanese-gpt-1b/resolve/main/config.json".into(),
        cache_subdir: "japanese-gpt-1b/config".into(),
    });
    let generate_config = GenerateConfig {
        config_resource,
        ..Default::default()
    };

    Ok(())
}

```

**Comment by ycat3** [comment]
Thank you Guillaume-be.
It works.
I am going to publish a japanese pretrained and finetuned gpt2 1.3B model for rust and pytorch at hugging face models hub.
I will let you know when ready.

**Comment by ycat3** [comment]
FYI.
I published the japanese pretrained and finetuned GPT2 1.3B rust model.

https://huggingface.co/jweb/japanese-soseki-gpt2-1b
https://jweb.asia/

**Comment by guillaume-be** [comment]
Hello @ycat3 ,

I see in https://github.com/guillaume-be/rust-bert/issues/231 that you now have the model working, this is great!
I am closing this issue for now - please feel free to reach out if you face some additional issues.
