### ISSUE TITLE
What exact model is downloaded when using `Gpt2ModelResources::GPT2`?

### ISSUE THREAD

**Issue by johannesvollmer** [guillaume-be/rust-bert#23]
First, thanks for you work! 

I would like to know which exact model is downloaded from from `...models.huggingface.co/bert/gpt2-rust_model.ot`.  Is this the 1.5B model?

**Comment by guillaume-be** [comment]
Hello,

The default model currently included in dependencies is GPT2 small (12 layers, 768 hidden dimension). If larger models are of interest I could run the conversion and upload them as well.

**Comment by julien-c** [comment]
Hi @johannesvollmer by the way you can also check on the model page's list of files here: 

https://huggingface.co/gpt2#list-files

`"gpt2"` is the model id for the small 117M model.

**Comment by johannesvollmer** [comment]
Thank you both so much for your quick answers! <3

I would be very happy if you could spend your time to convert the largest model.

**Comment by johannesvollmer** [comment]
Thank you both so much for your quick answers! <3

I would be very happy if you could spend your time to convert the largest model.

**Comment by guillaume-be** [comment]
Sure, I'll push an update over the week-end

**Comment by johannesvollmer** [comment]
Thank you :)
