### ISSUE TITLE
libtorch 1.11.0

### ISSUE THREAD

**Issue by ycat3** [guillaume-be/rust-bert#232]
rust-bert example programs are working with torch-sys v0.7.0, tch v0.7.0 for libtorch 1.11.0.
When will you update rust-bert crate ?

**Comment by guillaume-be** [comment]
Hello @ycat3 ,

I will update the crate with the new release of `tch` later tomorrow after some further platform/device testing.

**Comment by guillaume-be** [comment]
Fixed by https://github.com/guillaume-be/rust-bert/pull/233
