### ISSUE TITLE
mt5 model support ?

### ISSUE THREAD

**Issue by OElabs-official** [guillaume-be/rust-bert#234]
https://huggingface.co/csebuetnlp/mT5_multilingual_XLSum
Looks like a great multilingual summarization model 
I try to use  ModelType::T5
and report >>>
`thread 'main' panicked at 'could not parse configuration: Error("missing field `task_specific_params`", line: 31, column: 1)', /home/akitsuki/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.17.0/src/common/config.rs:42:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

copy config from T5 and reported
thread 'main' panicked at 'could not parse configuration: Error("missing field `max_position_embeddings`", line: 61, column: 1)', /home/akitsuki/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-bert-0.17.0/src/common/config.rs:42:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by guillaume-be** [comment]
Hello @OElabs-official ,

Thank you for sharing this model. The current T5 implementation was indeed lacking some options for mT5 compatibility. I am pushing some changes as part of https://github.com/guillaume-be/rust-bert/pull/236 that will allow loading the mT5 model you shared. I have verified the output is identical to the Python version with the following settings:

```rust
extern crate anyhow;

use rust_bert::pipelines::common::ModelType;
use rust_bert::pipelines::generation_utils::LanguageGenerator;
use rust_bert::pipelines::summarization::SummarizationConfig;
use rust_bert::resources::LocalResource;
use rust_bert::t5::T5Generator;
use std::path::PathBuf;
use tch::Device;

fn main() -> anyhow::Result<()> {
    let config_resource = Box::new(LocalResource {
        local_path: PathBuf::from("path/to/config.json"),
    });
    let vocab_resource = Box::new(LocalResource {
        local_path: PathBuf::from("path/to/spiece.model"),
    });
    let model_resource = Box::new(LocalResource {
        local_path: PathBuf::from("path/to/rust_model.ot"),
    });

    let summarization_config = SummarizationConfig {
        model_type: ModelType::T5,
        model_resource,
        config_resource,
        vocab_resource: vocab_resource.clone(),
        merges_resource: vocab_resource,
        device: Device::cuda_if_available(),
        min_length: 0,
        max_length: 84,
        no_repeat_ngram_size: 2,
        num_beams: 4,
        ..Default::default()
    };

    let model = T5Generator::new(summarization_config.into())?;

    let input = ["This is a text to summarize."];

    let output = model.generate(Some(&input), None);
    for sentence in output {
        println!("{}", sentence.text);
    }

    Ok(())
}

```
