### ISSUE TITLE
"Extract" Keywords from text

### ISSUE THREAD

**Issue by felippemr** [guillaume-be/rust-bert#237]
👋  How can I "extract" keywords from some text using this crate? 

I was following [this article](https://towardsdatascience.com/keyword-extraction-python-tf-idf-textrank-topicrank-yake-bert-7405d51cd839) for python and was wondering if I could do something similar using rust-bert.

I am a NLP noob trying to learn, so take this with a grain of salt. Thanks for the great work on this!

**Comment by guillaume-be** [comment]
Hello @felippemr ,

The example linked in this article leverages `KeyBERT` which is not yet supported in this crate. I am planning on implementing sentence embeddings transformers over the next few weeks which seems to be at the basis of KeyBERT - so this feature may be implemented in the near future.
