### ISSUE TITLE
Question: Device::Cuda throwing an Error

### ISSUE THREAD

**Issue by johannesvollmer** [guillaume-be/rust-bert#24]
Hi, thanks for your work, again. I have a long story for you this time.

### Problem
I had a project running a simple GTP-2 Generator. The CPU version ran just fine (albeit rather slow, as expected). Then I tried running the CUDA version to utilize the GPU. I got the following (probably torch related) runtime error:

`TorchError { c_error: 
    "Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don\'t directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don\'t depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library. (initCUDA at C:\\b\\windows\\pytorch\\aten\\src\\ATen/detail/CUDAHooksInterface.h:63)\n(no backtrace available)"
}
`

### Trying to fix it

I could not run the check as I am running Windows and do not have the `ldd` command available.

I realized that I didn't even have CUDA installed for my **GTX-1060 on Windows**, so I did that and the installation finished successfully, but the project didn't work yet. The `tch` crate states that the TorchLib dependency should be installed automatically in a build script. I thought maybe that's the thing that didn't work, so I installed TorchLib `1.5` manually, as advised in their README, setting PATH and TORCHLIB environment variables to the directory of the extracted library. 

I noticed rust-bert uses version `0.1.6` of tch, which is only compatible with PyTorch `1.4`. However, I cannot find a place to download TorchLib `1.4`, not even on [PyTorch.org](https://pytorch.org/get-started/previous-versions/). I also tried using tch version `1.7` in my cargo project, which also did not work.

### The actual Question, finally
**I know this is possibly not at all related to rust-bert itself, but if anyone of you has an idea that may help, I'd be happy if you wrote a little comment hinting me in the right direction.**

Have a great weekend, all of you! :)

**Comment by guillaume-be** [comment]
CUDA related issues are very difficult to troubleshoot as they depend on a lot of local settings. Note that the minimum dependency for `rust-bert` is `tch-rs>=0.1.6`. A clean compilation will actually install using the latest version `0.1.7`.

A few ideas:
- make sure your Nvidia drivers are up to date
- Install CUDA 10.1
- try turning off your environment variables for LIBTORCH, on windows this was not helping in my case
- set the environment variable  for your account `TORCH_CUDA_VERSION` to `10.1`
- Delete your compilation target folder to force a clean re-compilation of `tch-sys`

**Comment by johannesvollmer** [comment]
Thanks for your input, I'll try those today!

**Comment by johannesvollmer** [comment]
I noticed I have CUDA version 10.2 (.89). Is it strictly required to use 10.1?

**Comment by guillaume-be** [comment]
This should also work. You then need to set the `TORCH_CUDA_VERSION` to `10.2`
For your reference, `tch` build `tch-sys` which sets-up the CUDA environment for the crate. The detailed script can be found here (https://github.com/LaurentMazare/tch-rs/blob/master/torch-sys/build.rs).

The LIBTORCH library is downloaded automatically in windows by building the following url:
`https://download.pytorch.org/libtorch/<CUDA_VERSION>/libtorch-win-shared-with-deps-<TORCH_VERSION>.zip`

Replacing CUDA_VERSION by cu102 and TORCH_VERSION by 1.5.0 creates a valid url:
[https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.5.0.zip](https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.5.0.zip)

**Comment by johannesvollmer** [comment]
That's what I tried:
- deleted the target directory to rebuild from scratch
- set TORCH_CUDA_VERSION `10.2`
- set TORCH_CUDA_VERSION `cu102`
- remove `LIBTORCH` environment variable (but keep in in PATH)

I always got a different error, even after restoring the previous environment variable state (which previously worked fine):
`error: process didn't exit successfully: `target\release\phrase-set-variations.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)`

I have never had this error before and was not able to find a solution via Google

**Comment by guillaume-be** [comment]
Does this error occur at compilation or at runtime? You may have more luck posting this issue on the `tch` repository. I guess this is related to the set-up of this library rather than the language models themselves.

Is Pytorch or Tensorflow working correctly with your current CUDA setup?

**Comment by johannesvollmer** [comment]
Yeah, good idea. Also, I'm just updating my graphics drivers, which I thought already happened, but actually only downloaded, oops. I'll post an issue on `tch` if updating drivers does not work.

**Comment by johannesvollmer** [comment]
Thanks nevertheless for your support! :)
