### ISSUE TITLE
How to save trained model with rust-bert?

### ISSUE THREAD

**Issue by winston0410** [guillaume-be/rust-bert#241]
Thank you for your effort in creating this crate. I have read the tutorial and I understand how to use models in this crate, but I can't find any function for saving trained model. Is this function missing right now, or I have missed something?

**Comment by guillaume-be** [comment]
Hello @winston0410,

You can use the `VarStore` holding the model parameters to save it, using the [save](https://docs.rs/tch/latest/tch/nn/struct.VarStore.html#method.save) method as follows:

```rust
use tch::nn;
use rust_bert::bert::BertForMaskedLM;

let mut vs = nn::VarStore::new(device);
let bert_model = BertForMaskedLM::new(&vs.root(), &config);

[training...]

vs.save("path/to/destination.ot")?;
```

**Comment by winston0410** [comment]
@guillaume-be That is very helpful. Thanks!
