### ISSUE TITLE
gpt dialog issues after shallow clone optimizations

### ISSUE THREAD

**Issue by Miezhiko** [guillaume-be/rust-bert#244]
getting:

`Err` value: Torch("unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.\nException raised from assert_no_overlap at ../aten/src/ATen/MemoryOverlap.cpp:96 (most recent call first):\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b

**Comment by guillaume-be** [comment]
Hello @Miezhiko ,

Thank you for raising this. I did run the test and did not observe this issue. Could you please share an example reproducing the error - or the full stack trace so that I could identify the tensor causing issues?

Thank you!

**Comment by Miezhiko** [comment]
will be hard, can't promise if I can do it fast, I've dropped patch already to repair things fast

there is code which was causing error: https://github.com/Miezhiko/Amadeus/blob/mawa/Mozart/src/bert/chat.rs#L61

**Comment by Miezhiko** [comment]
@guillaume-be have you found root of issue of it still will need to have research?

**Comment by guillaume-be** [comment]
Hello @Miezhiko ,

I have reverted the changes for now as they would require some further research. If you are able to reproduce the error it would be very helpful - otherwise I will investigate on my end before pushing these changes again.
