### ISSUE TITLE
Should there be default for configuration like transformer?

### ISSUE THREAD

**Issue by winston0410** [guillaume-be/rust-bert#248]
For example, all fields in `XLNetConfig` has a default value: https://huggingface.co/transformers/v2.9.1/model_doc/xlnet.html#xlnetconfig

But right now `Default` is not impl for any configuration, is there a particular reason for that?

https://docs.rs/rust-bert/latest/rust_bert/xlnet/struct.XLNetConfig.html

**Comment by winston0410** [comment]
Also I am trying to build a tokenizer with XLNet, and in `transformers` there is a parameter called [`vocab_file`](https://huggingface.co/transformers/v2.9.1/model_doc/xlnet.html#transformers.XLNetTokenizer), which contains the raw data for training the model. But I cannot find similar field to pass the data through the configuration. Is that missed or I should feed the model in other ways?

**Comment by guillaume-be** [comment]
Hello @winston0410 ,

This is correct - the configurations are missing a `Default` implementation as of now. There is no specific reason for that - they were mostly meant to be created from serialized configuration files found on the Hugging Face model hub (`config.json` files). This is a good suggestion I will add this implementation to configurations in this crate as well based on the defaults proposed in the reference Python implementation.

The XLNet implementation in `rust_tokenizers` also takes a vocabulary file as an input, see the [`from_file` constructor]( https://docs.rs/rust_tokenizers/latest/rust_tokenizers/tokenizer/struct.XLNetTokenizer.html#method.from_file). Is this the parameter you were looking for?

**Comment by winston0410** [comment]
That's great to know, and think all fields has to be set `Option<T>`, if we follow the implementation of huggingface completely. I think can contribute that, but it would be great if you make a commit on a random model first so that I understand your standard and avoid changing back and forth from review.

Yes the `from_file` field is what I am looking for, but then how can I feed data into the [XLNetForTokenClassification](https://docs.rs/rust-bert/latest/rust_bert/xlnet/struct.XLNetForTokenClassification.html) model, or any other XLNet model in `rust_bert`?

**Comment by guillaume-be** [comment]
@winston0410 The selection of the `Optional` fields in the configuration is currently made to allow the parsing of common configuration files stored on the Model Hub. Most of the fields in these configuration are actually not optional (the model could not be created if they are left to `None`). An alternative would be to fall back to default values within the model but I believe it makes the code significantly less readable so they will likely not all be default to `Optional`

https://github.com/guillaume-be/rust-bert/pull/251 implents `Default` for all models in this crate.

I am not sure I understand your second question. Can you please have a look at the example for an illustration of how these models are created and can be interacted with?
