### ISSUE TITLE
Conversation model examples should show how to continue a conversation

### ISSUE THREAD

**Issue by sloganking** [guillaume-be/rust-bert#286]
https://docs.rs/rust-bert/0.19.0/rust_bert/pipelines/index.html#4-dialogue-model

It looks like #87 might show how to continue a conversation with the `add_user_input()` part of

```rust
let _ = conversation_manager
    .get(&conversation_1_id)
    .unwrap()
    .add_user_input("Is it an action movie?");
```

But the official docs do not.

**Comment by guillaume-be** [comment]
Hello @sloganking ,

Thank you for raising this - you are right this was missing from the docs. I am pushing an update to illustrate how to work with multi-turns conversations.
