### ISSUE TITLE
Generate sequence with max_new_tokens

### ISSUE THREAD

**Issue by lerouxrgd** [guillaume-be/rust-bert#290]
Hello @guillaume-be ,

In HF `transformers` there is the [max_new_tokens](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate.max_new_tokens) parameter that defines maximum numbers of tokens to generate, ignoring the number of tokens in the prompt.

It looks like this is not doable with current implementation of [generate_indices](https://github.com/guillaume-be/rust-bert/blob/78da0f4814da00139551b615d6d06e7e92f59a79/src/pipelines/generation_utils.rs#L1750-L1764).

I can think of various approaches to fix this:
- Change `max_length` to `max_length: Option<i64>` (default `Some(current_val)`) and add `pub max_new_tokens: Option<i64>` (default `None`) in `GenerateConfig`, and then have the same behavior as HF `transformers` (if `max_length` and `max_new_tokens` are both defined, then it [throws an error](https://github.com/huggingface/transformers/blob/v4.23.1/src/transformers/generation_utils.py#L1305-L1311))
- Add a new parameter `pub max_new_tokens: Option<i64>` (default `None`) in `GenerateConfig`
  When it is present, ignore `max_length` and use input prompt + max_new_tokens
- Add a new parameter `pub max_length_ignore_prompt: bool` (default `false`) in `GenerateConfig`
  When true, generate a seq of `max_length` + input prompt
- Something else ?

I can prepare a PR with the solution you prefer.

**Comment by guillaume-be** [comment]
Hello @lerouxrgd ,

It is possible to pass `max_new_tokens` in the `GenerateOptions` in the `generate`, `generate_indices` and `generate_from_ids_and_past` methods: https://github.com/guillaume-be/rust-bert/blob/78da0f4814da00139551b615d6d06e7e92f59a79/src/pipelines/generation_utils.rs#L1510

The behaviour seems to be aligned with that of the Python library: https://github.com/huggingface/transformers/blob/2e35bac4e73558d334ea5bbf96a1116f7c0d7fb3/src/transformers/generation_utils.py#L1358

The configuration is currently stored in two separate configuration objects: a `GenerateConfig` with options likely to be kept static during the life of the language generator and `GenerateOptions` where options that are likely to vary from generation to generation can be provided. - this may impact discoverability of the  generation features indeed.

I hope this helps

**Comment by lerouxrgd** [comment]
Oh thank you for pointing that out, I was actually using `TextGenerationModel` instead of directly `GptJGenerator` (or something similar), and there the `generate` method doesn't take a `GenerateOptions` (but only a prefix).

However there is something that boggles me, even though I specify `max_new_tokens` (to be 32 for instance), it looks like the generated output is of the same length as the input when the input is a bit long.

For instance this looks correct:
- **Input:** Animals in space originally served to test the survivability of spaceflight,
- **Output:** Animals in space originally served to test the survivability of spaceflight, but they have also been used to study the effects of microgravity on the human body. The effects of spaceflight on the human body are complex and include changes

But this looks shortened:
- **Input:** Animals in space originally served to test the survivability of spaceflight, to evaluate the effects of microgravity on living systems, and to determine the effects of radiation on human health. It was learned that animals in orbit were subject to
- **Output:** Animals in space originally served to test the survivability of spaceflight, to evaluate the effects of weightlessness on the human body, and to study the effects of microgravity on the human body. The first animal in space was a dog named Laika,

It looks like the prompt is being re-written at a certain point and the generated length looks smaller than input length + max_new_tokens.
Do you have any idea of what could be the reason ?

**Comment by guillaume-be** [comment]
Hello @lerouxrgd ,

Could you please share an example to reproduce the issue? I did a quick check on my side and the `max_new_token` parameter seems to be working as expected:
```rust
use rust_bert::gpt2::{
    GPT2Generator, Gpt2ConfigResources, Gpt2MergesResources, Gpt2ModelResources, Gpt2VocabResources,
};

use rust_bert::pipelines::generation_utils::{GenerateConfig, GenerateOptions, LanguageGenerator};
use rust_bert::resources::RemoteResource;

use tch::Device;

fn main() -> anyhow::Result<()> {
    let config_resource = Box::new(RemoteResource::from_pretrained(Gpt2ConfigResources::GPT2));
    let vocab_resource = Box::new(RemoteResource::from_pretrained(Gpt2VocabResources::GPT2));
    let merges_resource = Box::new(RemoteResource::from_pretrained(Gpt2MergesResources::GPT2));
    let model_resource = Box::new(RemoteResource::from_pretrained(Gpt2ModelResources::GPT2));

    let generate_config = GenerateConfig {
        max_length: 56,
        model_resource,
        config_resource,
        vocab_resource,
        merges_resource: Some(merges_resource),
        do_sample: false,
        num_beams: 1,
        device: Device::Cpu,
        ..Default::default()
    };
    let model = GPT2Generator::new(generate_config)?;

    let input_context_1 = "Rust is a";
    let input_context_2 = "There was a ";

    let generate_options = GenerateOptions {
        output_scores: true,
        max_new_tokens: Some(5),
        ..Default::default()
    };

    let output = model.generate(
        Some(&[input_context_1, input_context_2]),
        Some(generate_options),
    );

    for output in output {
        println!("{:?}", output.text);
    }
    Ok(())
}
```

returns:
```
"Rust is a very simple and powerful library"
"There was a urn in the room,"
```

I am not sure I understand what you  mean by 
> the prompt is being re-written at a certain point

**Comment by lerouxrgd** [comment]
If I try your example with a long example and `max_new_tokens: Some(32)` I have indeed correct results:

- **Input:** <ins>Animals in space originally served to test the survivability of spaceflight, to evaluate the effects of microgravity on living systems, and to determine the effects of radiation on human health. It was learned that animals in orbit were subject to</ins>
- **Output:** <ins>Animals in space originally served to test the survivability of spaceflight, to evaluate the effects of microgravity on living systems, and to determine the effects of radiation on human health. It was learned that animals in orbit were subject to</ins> a range of physiological and behavioral changes, including increased body temperature, increased body weight, and increased body mass. The animals were then subjected to a series of tests

And the output correctly contains the input prompt + 32 new tokens.

However if I remove `max_length: 56` (As in Python we are supposed to set either `max_length` or `max_new_tokens`, but not both). Then for the same input I get:

- **Output:** <ins>Animals in space originally served to test the survivability of spaceflight, to evaluate the effects of</ins> space flight on the human race, and to assess the effects on the environment of space travel on human health.\n\nThe study was funded by the National Science

Where the output doesn't contain the whole input prompt, only its beginning, the rest (which is different) is what I called "re-written". I would expect the whole input prompt to be part of the output, even if I don't specify any `max_length`, is this incorrect ?

So now my understanding is that we have to set `max_length` to something we know will be longer that input prompt + max_new_token if we want to really have output = input + max_new_token ?

**Comment by guillaume-be** [comment]
Hello @lerouxrgd ,

You are absolutely correct, the current implementation truncates the input to `max_length` for long input prompts. I am pushing an update that makes `max_length` optional (mirroring the behaviour of the Python implementation) and allows passing long prompts for generation (see https://github.com/guillaume-be/rust-bert/pull/296)
