### ISSUE TITLE
Failure library is being deprecated

### ISSUE THREAD

**Issue by proycon** [guillaume-be/rust-bert#30]
I happened to come across the news that the failure crate is being deprecated, and was aware this library is used by rust-bert: see  rust-lang-nursery/failure#347

This probably isn't a priority, but something you might want to be aware of at least.

**Comment by guillaume-be** [comment]
Hello,

I agree and have seen the news too. For now `rust-bert` relies on `tch-rs` which still uses Failure. I am keeping the dependency for a similar "feel" between the two libraries. I would recommend raising it to the `tch-rs` author. If required the Failure crate is only lightly used and replacing the `Faillible<()>` by `Result<T, Err>` should not require too much effort.

Thank you for raising this
