### ISSUE TITLE
translation_mbart.rs Mismatched Types

### ISSUE THREAD

**Issue by junque1r4** [guillaume-be/rust-bert#305]
Almost all examples are with this kind of errors...
[Example](https://github.com/guillaume-be/rust-bert/blob/master/examples/translation_mbart.rs)
https://app.warp.dev/block/jll6r8juSz00KmymiJLDdE

**Comment by guillaume-be** [comment]
Hello @junque1r4 ,

I am unable to reproduce - all examples are working for me. Which version/commit are you using?

**Comment by junque1r4** [comment]
I'm without time to reproduce again, thank's anyway

**Comment by junque1r4** [comment]
.
