### ISSUE TITLE
Generic HttpError when attempting to fetch any RemoteResource

### ISSUE THREAD

**Issue by jkoudys** [guillaume-be/rust-bert#306]
I have this working in my local environment (M1 mac mini, rust-bert 0.19.0), where it fetches the default for ZeroShotClassifier, bart-large-mnli. I deploy it to my digitalocean droplet (ubuntu, inside a docker container also ubuntu), and the following comes back with a `RustBertError::FileDownloadError(cached_path::Error::HttpError)`. This HttpError has no info and is what gets thrown if none of the other (more descriptive) reqwest errors happen.

I see that it creates the `~/.cache/.rustbert/bart-large-mnli` directory. If I try to copy up my local `bart-large-mnli` into that path, it still fails with the same HttpError. 

What could be failing here? I feel like at very least, there's an issue with the error reporting, as I'm clearly getting an error that's having its information stripped out. Right now it could be too many things (does libcurl need to be installed? libssl? ) I've at least verified that I can connect to the resource it's trying to download using command-line curl.

**Comment by guillaume-be** [comment]
Hello @jkoudys ,

The error handling probably comes from the [cached-path](https://github.com/epwalsh/rust-cached-path) crate, with the following section probably hiding the error message you are looking for: https://github.com/epwalsh/rust-cached-path/blob/5e49e5f1db136436fee10966858ff476b0cded18/src/error.rs#L63.

I agree the error message should probably pass on the output from `reqwest` to make debugging easier. You may need to raise an issue on the [cached-path](https://github.com/epwalsh/rust-cached-path), unless @epwalsh reads this?

Have you tried running in a more verbose mode?

**Comment by epwalsh** [comment]
I have a PR in the works in `cached-path` to address this: https://github.com/epwalsh/rust-cached-path/pull/67

**Comment by epwalsh** [comment]
Just released that change in `cached-path` version 0.6.0.

**Comment by guillaume-be** [comment]
Thank you very much @epwalsh for the quick update - I just tested it and your update should address this issue. Bumping the `cached-path` dependency in https://github.com/guillaume-be/rust-bert/pull/310

**Comment by jkoudys** [comment]
Great, this addresses my problem. Thanks @epwalsh ! Better response on an open source project than most commercial ones :)

**Comment by epwalsh** [comment]
Glad to hear it!
