### ISSUE TITLE
Compiling / Running in docker

### ISSUE THREAD

**Issue by i0n** [guillaume-be/rust-bert#307]
Hey all.

I've been experimenting with this but have run into a whole bunch of problems when trying to package everything up into a docker image for deployment.

rust-bert version 0.19.0

I have tried every combination of environment variables and LIBTORCH installs, but nothing works.
In dev (on a Mac) everything builds and runs as long as I do not set any LIBTORCH related environment variables using cargo run.
If I attempt to manually download v 1.13.0 of LIBTORCH then there is a big compile time explosion, presumably as a result of a mismatch in LIBTORCH versions.

Trying this method inside the docker container (rust 1.65 base) just results in compile time error.

rust-bert at master
Switching to rust-bert at master I have to make some changes to the config of my model, but everything continues to work in dev.
In the container the program now compiles and actually runs, but upon inserting input to the model the process exits and just outputs "killed" which is a pretty cryptic error, I have no idea what the problem is.

Is anybody else experiencing any of this?
Seems trivial to implement in dev but impossible to deploy. As I mentioned before I am using the rust:1.65 docker image as a base and adding version 1.13.0 of LIBTORCH in the manner suggested. Tried cpu gpu flavours with similar results.
The model itself (GPT_NE02.7B) is being mounted as a volume in the container.

**Comment by i0n** [comment]
Some more information on the above:

I discovered that using version 0.19.0 of rust-bert actually requires LIBTORCH 1.12.0 not 1.13.0 Not sure if it's just me but that wasn't clear.

The cryptic "Killed" error inside the docker container is actually to do with hitting the VM resource limits of the docker engine. Upping everything fixes the issue.

**Comment by rruckley** [comment]
Did you manage to get a working Dockerfile for the build? I'm working on building a container also and don't want to trip up over  similar issues.

**Comment by i0n** [comment]
Yes but it needed a massive resource allocation which I couldn't provide via docker desktop on my Mac. If you find a way to tame the requirements I'd love to know!

**Comment by rruckley** [comment]
How big a resource allocation? I have a VM I use for testing things like this but only have 16GB to play with.
