### ISSUE TITLE
Custom Long T5 model missing tensor values after conversion

### ISSUE THREAD

**Issue by copoer** [guillaume-be/rust-bert#314]
Howdy,

I am trying to convert this hugging face model to a rust model so I can use it for summarizing:
https://huggingface.co/pszemraj/long-t5-tglobal-base-16384-book-summary
The python conversion script works fine but when I try to the resulting model it gives me an error message saying their are missing weights. Is there a way to resolve this?

```
 TchError("cannot find the tensor named encoder.block.3.layer.0.SelfAttention.o.weight in rust_model.ot
```

**Comment by copoer** [comment]
It seems like long t5 will have to be implemented as its own type. I am not sure how hard this would be. It seems like it would need its own feed_forward_proj function called `gated-gelu`. Making it different then the normal T5 `relu`. 
It might require something like this?:
https://github.com/LaurentMazare/tch-rs/blob/cbe7938e093b422367b0d73ee36d9b6d7a3441aa/examples/stable-diffusion/main.rs#L658

It would be nice to be able to run long t5 due to its lower system requirements compared to Pegasus. It seems to be a very popular model recently.

**Comment by guillaume-be** [comment]
Hello @copoer ,

You are right that LongT5 has its own model architecture and that the corresponding model would have to be implemented in Rust. I will look into the implementation that seems to share some modules with T5, but it will probably take a few weeks to update the codebase to support this model.
