### ISSUE TITLE
fp16 and int8 support for CPU

### ISSUE THREAD

**Issue by sunilmallya** [guillaume-be/rust-bert#344]
When can we expect support for fp16 and int8 to run inference on CPU?

**Comment by okpatil4u** [comment]
You beat me to it @sunilmallya. @guillaume-be can you help us understand what would be a good starting point for this ? We (as in me and my team) would love to collaborate on this.

**Comment by okpatil4u** [comment]
Also please add int4 support to the list.

**Comment by okpatil4u** [comment]
Apologies for too many messages on this thread. Apparently this project uses Pytorch C++ api in the backend.

I think 8bit support should be enabled by default, but not I am not so sure. Maybe author can comment on this. 4bit is not supported.

**Comment by sunilmallya** [comment]
You can actually have a FP16 or 8-bit quantized model in pytorch and save it as .ot, but the loading in rust converts everything to FP64. There are a bunch of places that need to support the precision found while loading the ot file.

**Comment by guillaume-be** [comment]
Hello @sunilmallya ,

The conversion to full precision (float32) happens in the upstream torch bindings dependency. I have opened a proposal in the torch bindings crate for changing the behaviour (https://github.com/LaurentMazare/tch-rs/pull/758), this should fix the issues in this crate when the it gets merged and released. I do expect a number of issues linked to hard-coding of some operations precision and will leave this open for tracking. It would be great if you could support and report any issues after the upstream changes get released.

**Comment by guillaume-be** [comment]
Closing as the underlying Pytorch library does not support `fp16` for the majority of operations on CPU, and there is no path to overcome this limitation in the near future.
