### ISSUE TITLE
Cannot do Bert MaskedLM without pooler

### ISSUE THREAD

**Issue by kayshinonome** [guillaume-be/rust-bert#349]
The only possible way I could find to do bert masked lm without a pooler is to do this
```rust
    let bert_model = BertForMaskedLM {
        bert: BertModel::new_with_optional_pooler(&vs.root() / "bert", &config, false),
        cls: BertLMPredictionHead::new(&vs.root() / "cls", &config),
    };
```
But I do not believe `BertLMPredictionHead` is directly exposed in any manner

**Comment by guillaume-be** [comment]
Hello @kayshinonome ,
Thank you for raising this - you are absolutely right it is currently not possible to create the `BertForMaskedLM` model without pooler, even though this is obviously not used for Masked LM tasks. The [Python implementation](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py#L1314) therefore hardcodes the pooler setting to be `False`, and I am pushing some changes mirroring this behaviour to the crate.
