### ISSUE TITLE
tch::Cuda::is_available() returns False

### ISSUE THREAD

**Issue by pramodith** [guillaume-be/rust-bert#35]
Hi, thanks for the work put into the library it's awesome.

Using Windows 10.

I've been able to run the  transformers models on CPU, but not on GPU.

I see that
`tch::Cuda::is_available()` 
returns False.

This is despite the fact that I have Cuda installed on my system. 
**nvcc --version **
returns 
![image](https://user-images.githubusercontent.com/16939722/81960871-99467a80-95df-11ea-888d-cc482e98072c.png)

I've also donwloaded LibTorch and added it to my system path. Any guidance to get the model working on GPU would be appreciated.

**Comment by guillaume-be** [comment]
Hello @pramodith and thank you for the interest in the library.
This is an issue with the set-up of the `tch-rs` crate dependency. A user experienced similar issues with Windows a few days ago (see https://github.com/guillaume-be/rust-bert/issues/24). 

I am also running the library on Windows with CUDA 10.2 and am not experiencing issues so far. Please try the following and let me know if any of these help:
- try turning off your environment variables for LIBTORCH, on windows this was not helping in my case
- set the environment variable  for your account `TORCH_CUDA_VERSION` to `10.2` (or try `10.1`
- Delete your compilation target folder to force a clean re-compilation of `tch-sys`

If these do not help I suggest you open an issue on the [tch-rs](https://github.com/LaurentMazare/tch-rs) crate
