### ISSUE TITLE
GGML Models

### ISSUE THREAD

**Issue by danforbes** [guillaume-be/rust-bert#355]
Is it possible to use this crate with [GGML](https://github.com/ggerganov/ggml) models?

**Comment by guillaume-be** [comment]
Hello @danforbes ,

The crate currently only supports torch-based model (and will support ONNX models in the near future) with no immediate plans to support further backends. It is my understanding that there are some existing ports of ggml-based models such as [llama-rs](https://github.com/rustformers/llama-rs)

**Comment by danforbes** [comment]
Putting this here for other that may be looking https://docs.llm-chain.xyz/
