### ISSUE TITLE
how build rust-bert project on docker?

### ISSUE THREAD

**Issue by spursy** [guillaume-be/rust-bert#356]
how build rust-bert project on docker?

**Comment by ianpurton** [comment]
@spursy Most rust projects compile to an executable so or a rust-bert project you can use the same docker setup as for any rust project.

You'll probale need to include libtorch and if using a GPU take a look at https://blog.roboflow.com/use-the-gpu-in-docker/

**Comment by spursy** [comment]
I have do a demo, please refer to https://github.com/spursy/algo-rust-bert-demo
