### ISSUE TITLE
Getting the tokenizer of a sentence-embedding model

### ISSUE THREAD

**Issue by SpirosMakris** [guillaume-be/rust-bert#360]
Is there a way to get the tokenizer of a sentence embedding model?

The intended use case is the following:
I have a large text that needs to be split into smaller chunks. 
Each of these chunks will then encoded with one of the sentence-embedding models, provided by this crate,
and then stored in a vector database.

In order to do the chunking of the text, access to the tokenizer is needed so that after splitting a Vec of tokens, 
the text in each chunk can be reconstructed.

As far as I'm able to see, the tokenizer is what can perform the decoding, but it's not public.

Thanks!

**Comment by guillaume-be** [comment]
Hello @SpirosMakris ,

Thank you for raising this, you are right, these methods are until now not exposed. This has been a recurrent request for a number of pipelines, I am pushing some changes exposing `get_tokenizer(&self)` and `get_tokenizer_mut(&mut self)` methods for all pipelines, including sentence embeddings

**Comment by SpirosMakris** [comment]
Hi @guillaume-be 

Thank you so much for the swift reply and change!!
