### ISSUE TITLE
Extend resource API to allow loading data from non-file sources?

### ISSUE THREAD

**Issue by mweber15** [guillaume-be/rust-bert#366]
Currently, I can load weights/vocabularies/configuration either by putting them on disk or making them available via a URL and creating a `ResourceProvider` that refers to the right location. This is very flexible, but I would also like to have the option to load data that I already have in memory, or have some other handle to (i.e. a memory-mapped file). While I could write those things to a temporary location on disk and use the existing mechanism, this seems like an area where more flexibility could be generally useful. Is this something you would consider reviewing a change for, and if so are there any specific approaches that would be more or less preferable?

Some possibilities here would be allowing for the use of `impl Read` or `impl Seek` in places that currently expect `PathBuf`, or even allowing for `tch::Tensor` to be provided directly.

**Comment by guillaume-be** [comment]
Hello @mweber15 ,

This is an interesting idea and I would be opened to creating an `InMemoryResourceProvider` or something similar. Currently all models are registering their variable in a `VarStore` and the `load<T: AsRef<std::path::Path>>(&mut self, path: T)` is used to copy values from a file. This method in turn iterates through a `HashMap<String, Tensor>` and copies their values over to the `VarStore` variables: https://github.com/LaurentMazare/tch-rs/blob/70212a2141ec72da7f6cc43ac17e0af3490f3d2a/src/nn/var_store.rs#LL188C19-L188C19

I guess one approach would be to:
1. Create an `InMemoryResourceProvider` to be a container for a `HashMap<String, Tensor>`.
2. Create a method that takes both a `ResourceProvider` and a `VarStore` as an input and would either delegate to the `varStore.load` in the case of `LocalResourceProvider` or `RemoteResourceProvider`, or perform the copy/move operation above in the case of `InMemoryResourceProvider`
3. Update all `VarStore.load` in the crate with the method above

There may be better ways to do so, happy to exchange on these. Please also feel free to start working on a PR implementing the above if you would like

**Comment by mweber15** [comment]
Hi @guillaume-be!

Thank you for the direction. I hope to have a PR to discuss in more depth within another day or two.

In addition to wanting to load weights from an in-memory resource, I would also like to refer to other resources (i.e. the `config_resource` JSON data) that are loaded in memory, but not stored a file on disk. I haven't look at this in too much depth yet, but it seems like that would necessitate additional support from traits in [`rust-tokenizers`](https://github.com/guillaume-be/rust-tokenizers) as well. Is that also a change you would be open to?

**Comment by guillaume-be** [comment]
Tokenizer and configuration files are generally very small, and I am unsure if the added complexity of handling a high number of `InMemoryResourceProvider` types (e.g. tokenizer may expect a higher variety of inputs for their vocabulary and merges/model files) justifies the memory-mapping capabilities.

I suggest to start with the model weights where the value proposition seems clear, and separate further in-memory resources to a follow-up discussion if that is OK with you

**Comment by mweber15** [comment]
Definitely on-board with discussing further changes separately.

I've deviated a bit from your suggested approach, but hopefully what I've done is sensible. If not I'm happy to make changes.
