### ISSUE TITLE
Get sentence-embedding dimensions

### ISSUE THREAD

**Issue by SpirosMakris** [guillaume-be/rust-bert#369]
Hi. Is there a way to get the number of dimensions of the embeddings for a SentenceEmbeddingsModel?

The use case is: I want to store the embedding result in a vector store and the dimension of the vector is needed when creating a collection in e.g. Qdrant. 

I could do a one-off dummy encoding in new() and store it it my struct, but that seems a little wasteful.

Thank you

**Comment by guillaume-be** [comment]
Hello @SpirosMakris ,

I am pushing some changes in https://github.com/guillaume-be/rust-bert/pull/371, can you please give it a try and let me know if this works?

**Comment by SpirosMakris** [comment]
Hey @guillaume-be,

works great!!
Thank you very much!
