### ISSUE TITLE
Remote Bert models are unreachable

### ISSUE THREAD

**Issue by diptanu** [guillaume-be/rust-bert#373]
Just noticed the Bert models on Huggingface, are not available anymore. For example - https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json throws a 401 un-authorized

https://huggingface.co/sentence-transformers throws 404 - not sure what's going on here. But with this, I think the pipelines which rely on these models are not going to be usable unless we change the source and host them somewhere. 

Not sure if this is just me, a temporary glitch or others are seeing as well. Any thoughts?

**Comment by matthewgapp** [comment]
Huggingface is experiencing an outage: https://twitter.com/huggingface/status/1655760648926642178?s=20. You can download and unzip the sentence transformers here: https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/ and then use the local sentence embedding's builder [here](https://github.com/guillaume-be/rust-bert/blob/9fd7983878d500cd0d6abc2fc13696aa8618bfc6/src/pipelines/sentence_embeddings/builder.rs#L46)

**Comment by diptanu** [comment]
Going to close this. Thanks, @matthewgapp 

cc @guillaume-be Don't think issues are a good place for these types of conversations, might want to open up the "discussions" feature for this repo for open-ended conversations.
