### ISSUE TITLE
Wrong responses for ConversationModel and custom model resource

### ISSUE THREAD

**Issue by Emulator000** [guillaume-be/rust-bert#374]
I don't know what exactly is the issue but I cannot get DialoGPT to work with my pre-trained model.

The model was trained with a `csv` file that basically has two columns:
<table>
<tr>
<td>from</td>
<td>text</td>
</tr>
<tr>
<td>Dario</td>
<td>hi everyone!</td>
</tr>
<tr>
<td>[...]</td>
<td>[...]</td>
</tr>
<tr>
<td>Dario</td>
<td>how are you today?</td>
</tr>
</table>

Here the code that I'm using, very similar to the example provided:
```rust
    let conversation_model = ConversationModel::new(ConversationConfig {
        device: Device::cuda_if_available(),
        model_resource: weights_resource,
        merges_resource: Some(merges_resource),
        vocab_resource,
        config_resource,
        top_p: 1.,
        top_k: 40,
        temperature: 1.1,
        length_penalty: 1.2,
        num_beams: 2,
        min_length: 1,
        early_stopping: false,
        max_length: Some(256),
        do_sample: true,
        num_return_sequences: 2,
        ..Default::default()
    })?;
    let mut conversation_manager = ConversationManager::new();
    let _ = conversation_manager.create("qualche suggerimento?");
    println!(
        "{:#?}",
        conversation_model.generate_responses(&mut conversation_manager)
    );
```

The output for some reason is always:
```
{
    de6ef9d4-6aef-484d-81d9-cc1a2077cf43: "Dario",
}
```

And is always composed by one element, even if the configuration `num_return_sequences` is set to `2`.

If I use the `TextGenerationModel` instead, the text get completed correctly and I can read some good sense sentences.

Is this because is the trained model malformed or is something related to indexes? How can I access to right generated text?

Thanks for the help!

**Comment by guillaume-be** [comment]
Hello,

The conversation model calls the `generate_from_ids_and_past` from the generator, so if you are getting reasonable outputs using the `TextGenerationModel` or `Generator` directly it should also work for the conversation model.

The `ConversationModel` will not work properly if the `num_return_sequence` is greater than 1, as the conversation manager would have to handle an exponentially large response space at each conversation round. I would suggest setting this value to 1 and see if it fixes the behaviour.

If this does not fix the issue, you may want to check the input and output generated at the following locations: [1](https://github.com/guillaume-be/rust-bert/blame/9fd7983878d500cd0d6abc2fc13696aa8618bfc6/src/pipelines/conversation.rs#L899) and [2](https://github.com/guillaume-be/rust-bert/blame/9fd7983878d500cd0d6abc2fc13696aa8618bfc6/src/pipelines/conversation.rs#L902) and compare it with the tokens generated using the `ModelGenerator` for the architecture you are using.

**Comment by Emulator000** [comment]
Thanks for your response @guillaume-be, I managed to let `ConversationModel` work just changing how the model was trained, in fact the correct format for the training was something like:
<table>
<tr>
<td>response</td>
<td>context</td>
</tr>
<tr>
<td>hello!</td>
<td>hi everyone!</td>
</tr>
<tr>
<td>[...]</td>
<td>[...]</td>
</tr>
<tr>
<td>I'm fine thanks</td>
<td>how are you today?</td>
</tr>
</table>

Nice suggestions though, if something is not working properly I could look there then!
