### ISSUE TITLE
Example of generating multiple words 

### ISSUE THREAD

**Issue by sbeckeriv** [guillaume-be/rust-bert#38]
Hello,

What I would like to do is generate haikus.

 I read over the example code (https://github.com/guillaume-be/rust-bert/blob/master/examples/openai_gpt.rs)  and I am out of my depth. Is there a way to get 100 words or ask for a different word?  I know the `get` returns a tch::Tensor and I have been trying different function calls with little luck. I figured I would ask here as it could be a good example to add. 

Thank you,
Becker

**Comment by guillaume-be** [comment]
Hello @sbeckeriv ,

For language generation I recommend using the generation pipelines. These include a number of post-processing steps (top k/p decoding, beam search, temperature setting, limit repetition of tokens) that significantly improve the quality of the text generated. Language models tend to generate improbable or repetitive sequences when greedy decoding is used.

Please check the generation example which allows you to load custom GPT or GPT2 models. You can set the length of generated sequences to be of the desired length, and return several sequences at a time for your review.

Is this not matching your needs?

**Comment by sbeckeriv** [comment]
Hello, 

Thanks for the suggestion. I am trying to generate the sequence based on syllables not the over all length.  I dont see a way to inspect a word in the process. i could generate sequences until it randomly produces the correct amount of syllables?

Thanks again.
Becker

**Comment by guillaume-be** [comment]
Hello,

I am not entirely familiar with haikus, but have the understanding that they are sequences of words that form a fixed amount of syllabes. GPT2 was trained on a large corpus but without any restriction to stick to this "style" of writing. 

If you have a systematic way of counting syllabes in the output generated by the language model, you could indeed try to generate word by word (returning several sequences at a time) and repeat the sampling until you get a hit that matches the right number of syllabes. (an alternative would be to use the greedy decoding script (`examples/openai_gpt.rs`), filtering the vocabulary indices that do fit the required number of syllabes, and sample from these. You should take the last position of the tensor returned by the model to get the probabilities per vocabulary id).

This would however be very wasteful, and a more common approach may be to train or finetune a language model on a haikus datasets as to embed this writing style in the language model (as in this [example](https://www.brianweet.com/2019/06/16/write-ai-gpt-2-haiku.html). You could train a haiku GPT2 in Python and use it in the Rust library. Some post-processing and clean-up would likely be required in this case too, but the sequences generates by the models are likely to be better matching the desired style.

**Comment by sbeckeriv** [comment]
Hello,

Thank you for the insights and direct. I appreciate the time you have taken.  I will look in to training GPT2 in python. The link you have provided seems to be a good start. 

Thanks again,
Becker

One day I might make
a better haiku because
of your helpful insight.

```
Test pattern which middle
Concrete instances parses voted
Important theorems
```
