### ISSUE TITLE
Problem generating embedding for the model paraphrase-multilingual-MiniLM-L12-v2

### ISSUE THREAD

**Issue by mango009** [guillaume-be/rust-bert#405]
I prepared the `paraphrase-multilingual-MiniLM-L12-v2` model per the instruction in the example `sentence_embeddings_local.rs`. The model got converted with no problem. I then proceed to run the example with a slight modification 

```
// line 26, load the model we just converted 
let model = SentenceEmbeddingsBuilder::local("resources/paraphrase-multilingual-MiniLM-L12-v2")
```

But it failed with the error:

```
Error: Tokenizer error: File not found error: resources/paraphrase-multilingual-MiniLM-L12-v2/vocab.txt vocabulary file not found :No such file or directory (os error 2)
```

I can see that there are no such a file available in the directory `resources/paraphrase-multilingual-MiniLM-L12-v2` but looks like the SentenceEmbeddingsBuilder is looking for it.

How do I proceed?

Thanks for any help

**Comment by guillaume-be** [comment]
Hello @mango009 ,

This seems related to https://github.com/guillaume-be/rust-bert/issues/334 - can you please have a look at the PR opened in an attempt to address the issue and let me know if this works for you?

**Comment by guillaume-be** [comment]
Fixed via https://github.com/guillaume-be/rust-bert/pull/408
