### ISSUE TITLE
Make downloads asyncronous

### ISSUE THREAD

**Issue by Veetaha** [guillaume-be/rust-bert#42]
I failed to integrate this library into my application which natively uses `async/await` and `tokio`.
I simply cannot create a model, because I get 
```
thread 'main' panicked at 'Cannot start a runtime from within a runtime.
This happens because a function (like `block_on`) attempted to block the current thread 
```
every time I try to create `SentimentModel::new()`.
I may be a newbie in tokio, so I tried
```rust
let model = tokio::task::block_in_place(|| SentimentModel::new(Default::default())).unwrap();
```
But this didn't solve the problem.
Also doing this:
```rust
let model = tokio::task::spawn_blocking(|| SentimentModel::new(Default::default()).unwrap())
    .await.unwrap();
```
also doesn't work because `Rust` complaints about sending some internal `std::rc::Rc` between threads. Even wrapping it all with `Arc<Mutex<SentimentModel>>` doesn't help.
I am simply perplexed and don't know how to use this crate inside of `async fn`s...

**Comment by guillaume-be** [comment]
Hello,

The dependencies download is asynchronous. The code is located at: https://github.com/guillaume-be/rust-bert/blob/60bffe6e8ba227be4938848a6e8cc4181961f325/src/common/resources.rs#L182 
I believe the problem is that I declared a `#[tokio::main]` which would not allow you to do so in your main application.

I am pushing some changes to make the overall function synchronous and use a local runtime instead. As I do not have code available to reproduce the issue, could you please check-out the branch `async_download` and let me know if this solves the issue?

**Comment by Veetaha** [comment]
Sorry for not mentioning, basically the reproduction is:
```rust
use rust_bert::pipelines::sentiment::SentimentModel;

#[tokio::main]
async fn main() {
    let model = SentimentModel::new(Default::default()).unwrap();

    // or
    let model = tokio::task::block_in_place(|| SentimentModel::new(Default::default())).unwrap();

    // or the following which you cannot do due to rust complaining about sending Rc between threads
    let model = tokio::task::spawn_blocking(|| SentimentModel::new(Default::default()).unwrap())
        .await.unwrap();
}
```
It should produce the `Cannot start a runtime from within a runtime`

**Comment by guillaume-be** [comment]
Hello,

The library is by design currently synchronous, because the download part of it is a minimal feature.
To run the code in an asynchronous environment, please spawn a blocking thread:

```rust
#[tokio::main]
async fn main() {
    task::spawn_blocking(move || { let model = SentimentModel::new(Default::default()).unwrap(); });
}
```

**Comment by mooreniemi** [comment]
Hi! I found my way here having a similar issue and seeing [this SO](https://stackoverflow.com/questions/62536566/how-can-i-create-a-tokio-runtime-inside-another-tokio-runtime-without-getting-th), which didn't work for me. I was hoping to run `rust-bert` from within an async web server so I could make http requests to the model. I'm working with `warp`. However, I can't understand how to load the model and then be able to run the server in `[tokio::main]`. I understand the downloads are a minimal requirement, but is there no way to balance that requirement with hosting the model in a tokio runtime?
