### ISSUE TITLE
Upgrade Cargo dependencies

### ISSUE THREAD

**Issue by darxkies** [guillaume-be/rust-bert#434]
On Arch, rust-bert can not be compiled due to tch errors. With the newer version of tch (0.14.0) it works fine.

**Comment by volking0** [comment]
I am also encountering that, already have a PR ready for that https://github.com/guillaume-be/rust-bert/pull/426
Hopefully, it will get merged soon.

**Comment by guillaume-be** [comment]
As mentioned in https://github.com/guillaume-be/rust-bert/pull/426, unfortunately the latest version of tch causes errors when loading models that have been saved in half precision on a CPU (the CI for this PR is failing). I have raised an issue in the upstream repository (see https://github.com/LaurentMazare/tch-rs/issues/805) but this has not yet been addressed.
