### ISSUE TITLE
Support for OpenAIGPTDoubleHeadsModel, GPT2DoubleHeadsModel, SequenceSummary,AdamW

### ISSUE THREAD

**Issue by sachaarbonel** [guillaume-be/rust-bert#52]
Hi, I was trying to implement [Hugginface's ConvAI](https://github.com/huggingface/transfer-learning-conv-ai) when I realized those implementations were missing. Is it on the roadmap?  With some architecture guidance, I could make a PR.

I started something locally but I had some issues with SequenceSummary and couldn't figure out how to architecture my code. 

Here basically how I started architecturing this :

```rust
pub struct OpenAIGPTDoubleHeadsModel {
    transformer: OpenAiGptModel,
    lm_head: LinearNoBias,
    multiple_choice_head: SequenceSummary,
}

trait DoubleHeadModel {
 fn forward_t(
        &self,
        input_ids: &Option<Tensor>,
        attention_mask: &Option<Tensor>,
        token_type_ids: &Option<Tensor>,
        layer_past: Cache,
        position_ids: &Option<Tensor>,
        head_mask: &Option<Tensor>,
        input_embeds: &Option<Tensor>,
        mc_token_ids: &Option<Tensor>,
        labels: &Option<Tensor>,
        output_attentions: &Option<bool>,
        encoder_outputs: Option<&Tensor>,
        decoder_input_ids: &Option<Tensor>,
        train: bool,
    ) -> Result<
        (
            Tensor,
            Option<Tensor>,
            Cache,
            Option<Vec<Tensor>>,
            Option<Vec<Tensor>>,
        ),
        &'static str,
    >;}
}

#[derive(Debug, Serialize, Deserialize)]
/// # OpenAIGPTDoubleHeadsModel model configuration
/// Defines the OpenAIGPTDoubleHeadsModel model architecture (e.g. number of layers, hidden layer size, label mapping...)
pub struct OpenAIGPTDoubleHeadsConfig {
    pub attn_pdrop: Option<f64>,
    pub embd_pdrop: Option<f64>,
    pub hidden_dropout_prob: Option<f64>,
    pub afn: Option<GptActivation>,
    pub initializer_range: f64,
    pub layer_norm_epsilon: f64,
    pub n_ctx: i64,
    pub n_embd: i64,
    pub n_head: i64,
    pub n_layer: i64,
    pub n_positions: i64,
    pub num_labels: Option<i64>,
    pub num_classes: Option<i64>,
    pub output_past: Option<bool>,
    pub output_attentions: Option<bool>,
    pub output_hidden_states: Option<bool>,
    pub hidden_size: Option<i64>,
    pub resid_pdrop: Option<f64>,
    pub vocab_size: i64,
    pub summary_use_proj: Option<bool>,
    pub summary_proj_to_labels: Option<bool>,
    pub summary_first_dropout: Option<f64>,
    pub summary_last_dropout: Option<f64>,
    pub summary_type: Option<f64>,
}

impl Config<OpenAIGPTDoubleHeadsConfig> for OpenAIGPTDoubleHeadsConfig {}

impl OpenAIGPTDoubleHeadsModel {
pub fn new(p: &nn::Path, config: &OpenAIGPTDoubleHeadsConfig) -> OpenAIGPTDoubleHeadsModel {}
}

impl DoubleHeadModel for OpenAIGPTDoubleHeadsModel {
fn forward_t(
        &self,
        input_ids: &Option<Tensor>,
        attention_mask: &Option<Tensor>,
        token_type_ids: &Option<Tensor>,
        _layer_past: Cache,
        position_ids: &Option<Tensor>,
        head_mask: &Option<Tensor>,
        input_embeds: &Option<Tensor>,
        mc_token_ids: &Option<Tensor>,
        labels: &Option<Tensor>,
        output_attentions: &Option<bool>,
        _encoder_outputs: Option<&Tensor>,
        _decoder_input_ids: &Option<Tensor>,
        train: bool,
    ) -> Result<
        (
            Tensor,
            Option<Tensor>,
            Cache,
            Option<Vec<Tensor>>,
            Option<Vec<Tensor>>,
        ),
        &'static str,
    > 
}
}
```

**Comment by guillaume-be** [comment]
Hello @sachaarbonel ,

Could you please describe a bit further your use-case? Are you trying to implement a GPT/GPT2 model for language generation in the context of conversations? If so, the second head of the `OpenAIGPTDoubleHeadsModel` and `GPT2DoubleHeadsModel` is only used as a multitask objective during training (`BERT` next sentence prediction task), and is not needed at inference time.

As you can see in the `interact` script this specific model is not used, and the standard LM models are used for inference. The difference to the standard `generation` is that history is being recorded, the segment IDs are used to keep track of each conversation side and the decoding is simpler than the full-fledged `generation` normally used with beam search/top-p/top-k/temperature decoding.

I was planning to eventually implement the conversation capabilities, if you confirm this is of interest to you I can move this higher in my priority list.

**Comment by sachaarbonel** [comment]
Thank's for your quick response @guillaume-be, I was indeed trying to implement conversations. I didn't realize it wasn't needed at inference time. Looking forward to this feature.

**Comment by guillaume-be** [comment]
@sachaarbonel Do you have specific requirements for the ConvAI model? I was looking at available implementation and a more recent implementation from Microsoft called [DialoGPT](https://github.com/microsoft/DialoGPT) would also be available.

**Comment by sachaarbonel** [comment]
@guillaume-be I don't have specific requirements but it seems to me that DialoGPT is a better fit as I'm not very convinced by the personality approach of Hugginface (after some experiments with it)

**Comment by guillaume-be** [comment]
@sachaarbonel I have added multi-turn conversation capability in https://github.com/guillaume-be/rust-bert/pull/57. Please try it out and let me know if this is what you were looking for. So far the `medium` version of DialoGPT is available as a ready-to-use model.

**Comment by sachaarbonel** [comment]
Thank you for supporting this model @guillaume-be! I tried to run it on my mac (other models worked) and I'm getting this PyTorch error: ```bash
Error: TorchError { c_error: "[enforce fail at inline_container.cc:143] . PytorchStreamReader failed reading zip archive: failed finding central directory\nframe #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*) + 191 (0x108fa99cf in libc10.dylib)\nframe #1: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 131 (0x113e7de53 in libtorch_cpu.dylib)\nframe #2: caffe2::serialize::PyTorchStreamReader::init() + 315 (0x113e7ce1b in libtorch_cpu.dylib)\nframe #3: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::__1::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::__1::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 133 (0x113e7dd45 in libtorch_cpu.dylib)\nframe #4: torch::jit::load(std::__1::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::__1::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) + 120 (0x115485b38 in libtorch_cpu.dylib)\nframe #5: torch::jit::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, c10::optional<c10::Device>, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) + 103 (0x115485fa7 in libtorch_cpu.dylib)\nframe #6: at_load_callback_with_device + 114 (0x107ff83f2 in conversation)\nframe #7: tch::wrappers::tensor::Tensor::load_multi_with_device::h3cdf869685af4646 + 429 (0x10799ee0d in conversation)\nframe #8: tch::nn::var_store::VarStore::load::h1d3c6a9fb0c8ad5b + 63 (0x107994f5f in conversation)\nframe #9: rust_bert::pipelines::generation::GPT2Generator::new::h31195c4b189f1bbd + 1429 (0x1079d6e75 in conversation)\nframe #10: rust_bert::pipelines::conversation::ConversationModel::new::h979241362c26b122 + 881 (0x107996a91 in conversation)\nframe #11: conversation::main::hc6c491d2528533d2 + 61 (0x10798aded in conversation)\nframe #12: std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h3d8ed5424b557375 + 14 (0x10798ad8e in conversation)\nframe #13: std::rt::lang_start_internal::h026a2ad90a8dc9de + 441 (0x1081041e9 in conversation)\nframe #14: std::rt::lang_start::hb0a847d8103881d1 + 65 (0x10798ad71 in conversation)\nframe #15: main + 34 (0x10798b2c2 in conversation)\nframe #16: start + 1 (0x7fff64c273d5 in libdyld.dylib)\nframe #17: 0x0 + 1 (0x1 in ???)\n" }

``` 
Apparently it is due to the model [itself](https://github.com/pytorch/pytorch/issues/31620#issuecomment-600591415) but I'm not sure

**Comment by guillaume-be** [comment]
my mistake - forgot to upload the model. Can you please try again?

**Comment by sachaarbonel** [comment]
Nice it worked
