### ISSUE TITLE
EOF while parsing for EnglishToGerman translation

### ISSUE THREAD

**Issue by Qeenon** [guillaume-be/rust-bert#68]
Hello!

For default EnglishToGerman model tokenization fails with `EOF while parsing`

**Comment by guillaume-be** [comment]
Hello!

I am unable to reproduce (the base example in the library are running fine). Could you please share an example that is failing for you? 

Thank you!

**Comment by Qeenon** [comment]
@guillaume-be yes

```rust
async fn bert_translate(ctx: &Context, text: String, lang: Language)
          -> failure::Fallible<String> {
  ctx.set_activity(Activity::listening("Translating")).await;
  ctx.idle().await;
  let result = task::spawn_blocking(move || {
      let translation_config =
        TranslationConfig::new(lang, Device::cuda_if_available());

      let model = TranslationModel::new(translation_config)?;

      let output = model.translate(&[text.as_str()]);
      if output.is_empty() {
        error!("Failed to translate with TranslationConfig EnglishToRussian");
        Ok(text)
      } else {
        let translation = &output[0];
        Ok(translation.clone())
      }
    }).await.unwrap();
  ctx.online().await;
  result
}

#[command]
#[min_args(1)]
async fn en2de(ctx: &Context, msg: &Message, args: Args) -> CommandResult {
  let text = args.message().to_string();
  match bert_translate(ctx, text, Language::EnglishToGerman).await {
    Ok(out) => {
      channel_message(ctx, msg, out.as_str()).await;
    },
    Err(why) => {
      error!("Translation failed: {:?}", why);
    }
  }
  Ok(())
}
```

(Same code works for EnglishToFrench)

```
thread 'tokio-runtime-worker' panicked at 'could not parse vocabulary: Error("EOF while parsing a value", line: 1, column: 1258503) .cargo/registry/src/github.com-1ecc6299db9ec823/rust_tokenizers-3.1.6/src/preprocessing/vocab/marian_vocab.rs:56:44
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', 
```

Note that model is loading inside `spawn_blocking`, e.g. not in async mode and other models loads without errors

**Comment by guillaume-be** [comment]
@Qeenon the error occurs when loading the file. It could be that your vocabulary file got corrupted or did not download properly. Could you please try to delete the `spiece.model` file in `marian-mt-en-de` in your rustbert cache file (defaults to `~/.cache/rustbert/marian-mt-en-de` and try to start again to trigger the download?

**Comment by Qeenon** [comment]
Yes, thank you, re-downloading helped

**Comment by Qeenon** [comment]
@guillaume-be also something with FrenchToEnglish

TorchError { c_error: "[enforce fail at inline_container.cc:143] . PytorchStreamReader failed reading zip archive: failed fin...

what I can do with this? (can't find cache to clear)

**Comment by guillaume-be** [comment]
This appear to be another corrupted file, this time for the model weights. They should be located at `~/.cache/rustbert/marian-mt-ROMANCE-en/model.ot` if you used the default model.

**Comment by Qeenon** [comment]
works! thank you
