### ISSUE TITLE
Initial attempt at a REST API

### ISSUE THREAD

**Issue by tombh** [guillaume-be/rust-bert#78]
Thanks for this project, it's really helped me out.

So I thought I'd share my crude attempt at creating an API for this project. I'm just using it for the sentiment at the moment, but I'm planning to expand it to some other functions too. I'm posting here just in case anyone else is interested, or if anyone has any suggestions. Eg; I wonder if I'm instantiating `SentimentModel` in the best place to share memory usage between requests?

Maybe there's even interest in including this in the project here, if so I'd be happy to help.

https://github.com/tombh/rust-bert-api

**Comment by guillaume-be** [comment]
Hi @tombh and great idea!

I had a quick look at your repository and would have a few ideas for improvement:
- currently the model is loaded for every request. This is going to be wasteful and make the API slower than it has to be. Some large models may take several seconds to load in memory. Instead, you should load the model one time and re-use it for every request.
- When the load of the system will increase, you'll probably want to batch your inputs if you are using a GPU. You then need a simple queuing system to wait and collect inputs for some time before passing a batch to the model.

@epwalsh has already implemented a great example illustrating how to implement these ideas at https://github.com/epwalsh/rust-dl-webserver.

I believe there is value in having the core logic (language models) separated from applications (e.g. webserver). I would love to see a repository that leverages these language models in APIs though - and maybe you could look to contribute to https://github.com/epwalsh/rust-dl-webserver by adding new features and exposing more models?

**Comment by epwalsh** [comment]
@tombh contributions definitely welcome! I'd love to see `rust-dl-webserver` evolve into something more general and useful.

**Comment by tombh** [comment]
Thanks so much for the feedback! @epwalsh I had a look at your repo and got some inspiration thank you :) And @guillaume-be I took your advice and only load the model at boot. I haven't updated the repo yet, I'll update here when I do.

**Comment by zeyaddeeb** [comment]
I think I posted in a closed issue, is there a recommendation around this:

What is the best advice to follow this pattern

```rust
struct Model {
    sst: SentimentModel
}

impl Model {
    fn load() -> Self {
        let model = SentimentModel::new(Default::default()).unwrap();
        Model {
            sst: model
        }
    }
}

static MODEL: Lazy<Model> = Lazy::new(Model::load);

#[derive(Debug, Deserialize, Serialize)]
struct Context {
    text: String,
}


async fn generate(context: Context) -> Result<String, Rejection> {
    let input = [
            "Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it's not preachy or boring.",
    ];
    let output = MODEL.sst.predict(&input);
    Ok("output".to_string())
}

```

I tried using `batched_fn!`macro for zero-shot classification with no luck. Also the batching doesn't make a whole lot of sense for my use-case.

Is there a better way to load model once using `use once_cell::sync::Lazy;`

**Comment by guillaume-be** [comment]
Hello @zeyaddeeb ,

The `once_cell::sync::Lazy` requires the wrapped object to be `Sync`. This crate relies on **tch** whose `C_tensor` are not `Sync`, and therefore this pattern will not be feasible. 

I just tested again the `batched_fn!` macro and it works fine on my side: could you please indicate the error you are facing when using it? Note that this macro can be used with a batch size of 1 if batching is not desired.

**Comment by zeyaddeeb** [comment]
Here is the error:
```rust
`*mut torch_sys::C_tensor` cannot be shared between threads safely

`*mut torch_sys::C_tensor` cannot be shared between threads safely

help: within `sentiment_analysis::Model`, the trait `std::marker::Sync` is not implemented for `*mut torch_sys::C_tensor`
note: required because it appears within the type `tch::wrappers::tensor::Tensor`
note: required because it appears within the type `tch::nn::linear::Linear`
note: required because it appears within the type `rust_bert::bert::bert_model::BertForSequenceClassification`
note: required because it appears within the type `rust_bert::pipelines::sequence_classification::SequenceClassificationOption`

```
code is very similar to whats above

**Comment by guillaume-be** [comment]
Hello,

As mentioned using `once_cell::sync::Lazy` will not work because as highlighted by the error, `C_tensor` cannot be shared between threads safely. 

Could you please share the error you are facing when using the `batched_fn!` macro?

**Comment by zeyaddeeb** [comment]
no issues with `batched_fn!`, just was asking if there is another recommended way.

**Comment by MozarellaMan** [comment]
Sorry, was wondering if there is any solution for using a model that is global? I am also trying to create a REST API, but I'm not sure how to prevent the model from being loaded on every request without making the model global using `once_cell`. I get the same thread error shown above. I had a look at `batched_fn!` but in the docs it is somehow using `once_cell` to create a global model. As far as I've tried - this isn't possible

**Comment by guillaume-be** [comment]
Hello @MozarellaMan ,

You are right that `batched_fn!` relies on `once_cell` and therefore makes the model global. As far as I know the options are limited because the `C_tensors` cannot be shared safely between threads. 

I did have another look at https://github.com/epwalsh/rust-dl-webserver which uses `batched_fn!` to make predictions to ensure it still works well with Tokio 1.x - this seems to be the case. Maybe you could have a look at this implementation, it loads the model only once and then makes predictions while managing a queue for requests.

Not quite a REST API, but I am aware of another project using this library as a Discord bot which may be interesting for you to check: https://github.com/Qeenon/Amadeus. Looking at https://github.com/Qeenon/Amadeus/blob/mawa/src/steins/ai/bert.rs, it uses `once_cell::sync::Lazy` with `Mutex` to serve these queries.

**Comment by MozarellaMan** [comment]
@guillaume-be Thanks. This is exactly what I was looking for! I'm also trying to make a Discord bot :)

**Comment by paulbricman** [comment]
@MozarellaMan and others looking for more resources, I managed to get an API working. In my case, it wraps around text generation models, but it should be easy to adapt. Here's [the code](https://github.com/Psionica/Dual/blob/rust-backend/rust-backend/src/main.rs) (warning: my first Rust project, expect poor code quality). It's mainly ~~blatantly copied~~ adapted from [this other related resource](https://github.com/mooreniemi/envoy).
