### ISSUE TITLE
Request: Make private `model` inside ConversationManager public

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [guillaume-be/rust-bert#88]
I would like to discussing making the memebers of ConversationModel public. Here is why:

What I want to be able to do is take `past_user_inputs` and `generated_responses` from the conversation and regenerate `history`. `history` is the tokenized as ids representation of the history and is the actual input into the conversation model. Whereas `past_user_inputs` and `generated_responses` are string representations for output. This would allow me to trim the inputs to say `N` last inputs or make other adjustments.

Originally I tried something like this

- prepare `past_user_inputs` and `generated_responese` that I would like to make into the context
```rust
let texts: &[&str] = ....
```

- Replace history using this:

```rust
conversation.history = conversation_manager.model.get_tokenizer().convert_tokens_to_ids(
    conversation_manager.model.get_tokenizer().tokenize_list(texts.to_vec())
)
```

Unfortunalty I discovered that `conversation_manager.model` is private.

Would there be any negative issues with making it public or perhaps added a convenience method to recreate the inputs.

Alternatively just making `encode_prompts` public would suit my needs, but more general access to `model` would probably be more useful in the future

**Comment by guillaume-be** [comment]
Hello @QuantumEntangledAndy 

In general I would like to keep the pipelines at a higher level of abstraction, so maybe for this case there would be a solution not requiring manipulating the models and tokenizers directly. Note that 
```rust
conversation.history = conversation_manager.model.get_tokenizer().convert_tokens_to_ids(
    conversation_manager.model.get_tokenizer().tokenize_list(texts.to_vec())
)
```
would not generate a properly formed history, expecting `eos` tokens and actual token ids (`tokenize_list` returns a list of `String`).

Would it be more convenient if the pipeline was storing the history sequence (i.e. keep the sequence of prompts/responses separate as a Vec<Veci64>>) instead of an aggregated vector? This would probably be sufficient to trim to the last N inputs.

Would you still require access to the tokenizer? An alternative would be to load a tokenizer manually and use it to re-encode the prompts
```rust
tokenizer =   let tokenizer = Gpt2Tokenizer::from_file(vocab_path.to_str().unwrap(), merges_path.to_str().unwrap(), false,)?;
```

**Comment by QuantumEntangledAndy** [comment]
I would like a realiable what to read in history from a file too. Currently I save it as text (toml actually) with this format.

```rust
enum Speaker {
  Bot,
  User,
}

struct Past {
  speaker: Speaker
  idx: u64,
  message: String,
}
```

But on load I have noway of getting this data into the history.

**Comment by QuantumEntangledAndy** [comment]
Also if we do want to go down the abstraction route and focus on the higher level it might be better to not expose history at all. It is the tokenized and id form which is not realiably read or writable without the tokenizer.

**Comment by QuantumEntangledAndy** [comment]
What about a setup like this for the read part.


```rust
enum HistoryKind {
  Input,
  Output,
}
struct HistoryItem {
  kind: HistoryKind,
  message: Vec<i64>
}
struct Conversation {
  history: Vec<HistoryItem>
}

impl Conversation {
  pub fn get_outputs -> Vec<String> {
    self.history.filter(|i| i.kind == HistoryKind::Output).map(|i| tokens_to_string(i.message)).collect()
  }
  pub fn get_inputs -> Vec<String> {
    self.history.filter(|i| i.kind == HistoryKind::Input).map(|i| tokens_to_string(i.message)).collect()
  }
}
```

This doesn't solve my issue but it will change the model to one source of truth an set it up for easy filtering to N last input.

**Comment by QuantumEntangledAndy** [comment]
As a less invasive change we could:

- maintain the current input and reposnes strings and the source of actual input and outputs regardless of context that generated them.

- Change history to a list of list of ints split on the Eos

- Add methods to set and get the history as a list of strings.

**Comment by QuantumEntangledAndy** [comment]
Issue with getting and setting history as strings is that it requires the tokenizer which is not available to Conversation only to the manager so these two methods would have to be conversation manager method.

**Comment by guillaume-be** [comment]
@QuantumEntangledAndy thank you for providing more detail, I now understand better what you are trying to achieve.

> As a less invasive change we could:
> 
> * maintain the current input and reposnes strings and the source of actual input and outputs regardless of context that generated them.
> * Change history to a list of list of ints split on the Eos
> * Add methods to set and get the history as a list of strings.

These were my thoughts as well, pushing some changes that should allow you do load conversations from snapshots (see https://github.com/guillaume-be/rust-bert/pull/89)

**Comment by QuantumEntangledAndy** [comment]
Thanks I have tested #89 and can confirm that is it working as intended :)

**Comment by guillaume-be** [comment]
Thank you, merged https://github.com/guillaume-be/rust-bert/pull/89 to master
