### ISSUE TITLE
Make all models and pipelines `Send`

### ISSUE THREAD

**Issue by guillaume-be** [guillaume-be/rust-bert#91]
Hi @mfelsche,

Over the past few weeks I have worked on making all tokenizers `Send` to make multithreading in the library easier. With these changes, all pipelines and models could be also `Send`. I can see you have worked on a fork to ensure that these pipelines are `Send` for use in one of your projects.

Would you be interested in contributing these changes back to this repository? Changing the `TensorFunction` to a `Struct` and the methods to access the function `get_fn` would be welcome additions (https://github.com/mfelsche/rust-bert/commit/11409893d61afecc76145791d1b59bc4eab5170d and https://github.com/mfelsche/rust-bert/commit/80486069d1eed96eb6438e13c47bb2fdf24003ba)

**Comment by mfelsche** [comment]
Oh, nice that you noticed. I would very much love to contribute! :) Let me see where I can squeeze that in. I hope I can make it next week!

**Comment by guillaume-be** [comment]
Thanks @mfelsche ! I would like to include it in the next release of the library, which I was planning for the next few days. Do you have more visibility on your capacity for porting these changes back?

**Comment by mfelsche** [comment]
I will be able to do those changes by monday the latest. I hope to be able to do them earlier.
