### ISSUE TITLE
Slower than the Python Version

### ISSUE THREAD

**Issue by John0x** [guillaume-be/rust-bert#98]
Hey, I'm trying to avoid Python and therefore would love to use rust-bert instead of using the transformers directly.

Right now I'm using the GPT2 model, to generate some simple text, but I noticed that the Python+Tensorflow model is a lot faster than rust-bert and was wondering if I'm just doing something wrong.
Both are using the GPU.

Python:
```python
from transformers import pipeline, set_seed

generator = pipeline('text-generation', model='gpt2')
set_seed(42)
generator("Hello, I'm a language model,", max_length=30, num_return_sequences=5)
```

Rust:
```rust
    let generate_config = GenerateConfig {
        num_return_sequences: 5,
        ..Default::default()
    };
    let mut gpt2_generator = GPT2Generator::new(generate_config)?;
    let input_context = "Hello, I'm a language model,";

    let attention_mask = None;
    let max_length = 30;
    let decoder_start_token_id = None;

    let output = gpt2_generator.generate(
        Some(vec![input_context]),
        attention_mask,
        None,
        max_length,
        decoder_start_token_id,
    );
```

From rough estimation the python version is twice as fast.
Did anyone do some benchmarking to compare it to the tensorflow+python version?

**Comment by guillaume-be** [comment]
Hello @John0x and thank you for your interest in the library.

I have ran some benchmarks, although not for generation at this point. These benchmarks are available in `/benches` for classification, question answering, translation and summarization. These benchmarks generally showed similar performance for Python (Pytorch) and the Rust version for simple pipelines (e.g. classification) - and significant benefits for the Rust version for more complex pipelines (including generation-based models such as summarization). I am pushing some updated adding a benchmark for text generation as well: https://github.com/guillaume-be/rust-bert/pull/99.

Coming back to your example, I ran some benchmarks and I observe the Rust version running ~6x faster than the Pytorch version (both on GPU) using the base GPT2 model. On a RTX2070, 2700X with CUDA10.2 I observe the following:
- Rust: 435ms (average over 20 iterations)
- Python: 2960ms (average over 10 iterations)

Please note the following when comparing the implementations:
- The default settings for the Python pipeline are different than for Rust. Especially the  number of beams is 1 (Python) vs 5 (Rust). Python also defaults to no sampling while Rust will perform a sampling operation during generation. The settings for Python aligned with the Rust version are given in the script below.
- Did you compile Rust in `release` mode?
- When compiled in `release` mode, the Rust bindings tend to ignore the GPU, and run on CPU. Adding
```rust
    unsafe {
        torch_sys::dummy_cuda_dependency();
    }
```
at the beginning of the script seems to be an effective workaround to ensure the GPU is used, even in release mode.


The Rust benchmark script is available on the branch I am pushing now (https://github.com/guillaume-be/rust-bert/pull/99). The Python script I have run is as follows:

```python
import time
from transformers import pipeline

start = time.time()
generator = pipeline('text-generation', model='gpt2', device=0)
initialization = time.time()
print(f'Initialization: {initialization-start}')

num_iterations = 10
generation_times = []
for _ in range(num_iterations):
    iteration_start = time.time()
    outputs = generator("Hello, I'm a language model,",
                        max_length=30,
                        num_return_sequences=5,
                        num_beams=5,
                        do_sample=True,
                        temperature=1.0,
                        top_k=0,
                        top_p=0.9,
                        no_repeat_ngram_size=3
                        )
    iteration_elapsed = time.time() - iteration_start
    generation_times.append(iteration_elapsed)
    print(f'Elapsed: {iteration_elapsed}')

print(f'Average iteration time: {sum(generation_times)/len(generation_times)}')
```

I hope this helps.

**Comment by John0x** [comment]
Thanks for the fast response 👍 

Didn't know about the dummy_cuda_dependency stuff. That might have been the problem.
Thank you, you're a champ :)
